Documentation/02 Arguments, Options, and Flags.md
As the title says.
Great documentation by the way! 🎉 👏 👏
=> Remove extra whitespace in the documentation

Sources/ArgumentParser/Parsable Properties/Flag.swift, Tests/UnitTests/HelpGenerationTests.swift
This fixes https://github.com/apple/swift-argument-parser/issues/56
=> output default value in help for Flags built from CaseIterable enums

Sources/ArgumentParser/Parsable Types/ExpressibleByArgument.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
=> Don't show Optional(x) when displaying default values in help.

Sources/ArgumentParser/Utilities/StringExtensions.swift, Tests/ArgumentParserUnitTests/CMakeLists.txt, Tests/ArgumentParserUnitTests/StringSnakeCaseTests.swift
- Simplified the implementation of `String.convertedToSnakeCase(separator:)` method. (Maybe with some performance improvements as well.)
- Added related tests.
=> Simplify the implementation of String.convertedToSnakeCase

CHANGELOG.md
Preparing to tag the 0.0.5 release.
=> Update CHANGELOG for release 0.0.5

Documentation/02 Arguments, Options, and Flags.md
=> Fix documentation error in arguments/options/flags guide

Sources/ArgumentParser/CMakeLists.txt
- [x ] I've added at least one test that validates that my change is working, if appropriate
- [x ] I've followed the code style of the rest of the project
- [x ] I've read the [Contribution Guidelines](CONTRIBUTING.md)
=> Add missing file to cmake build

CHANGELOG.md
Preparing to tag the 0.0.6 release.
=> Update changelog for release 0.0.6

Package.swift, Tools/changelog-authors/main.swift
I've been using this to generate the list of contributors for each release.
=> Add a tool for getting the authors within a range of commits from GitHub

CMakeLists.txt, Sources/ArgumentParser/CMakeLists.txt, Sources/CMakeLists.txt, cmake/modules/SwiftSupport.cmake
This extends the CMake build to install the artifacts.  This is required
for redistribution of the build.
=> build: add support for installation

README.md
=> Update README with correct error message

Sources/ArgumentParser/Parsable Types/ExpressibleByArgument.swift
=> Omit "return" keyword

Tests/ArgumentParserUnitTests/ParsableArgumentsValidationTests.swift
=> Add comment about a compilation-only test

CHANGELOG.md
Fix minor typo in the CHANGELOG
=> fix minor typo

Sources/ArgumentParser/Completions/CompletionsGenerator.swift
Replacement for: https://github.com/apple/swift-argument-parser/pull/250
=> [Windows] Don't try to detect shell.

Examples/math/main.swift, Sources/ArgumentParser/Completions/BashCompletionsGenerator.swift, Sources/ArgumentParser/Completions/FishCompletionsGenerator.swift, Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift, Tests/ArgumentParserUnitTests/CompletionScriptTests.swift
=> Suppress hidden arguments from completion scripts

Tools/changelog-authors/main.swift
This change adds a `--repo` option to the `changelog-authors` tool that lets it work with other repositories. (I've been using it to help with Swift Algorithms changelog entries.
=> Allow changelog authors tool to work with other repos

Sources/ArgumentParser/CMakeLists.txt
Repair the build after #310 to allow building with CMake which is required for bootstrapping.
=> build: update CMakeLists.txt for new source

Sources/ArgumentParser/Documentation.docc/ArgumentParser.md
I added a link to ExperimentalFeatures.md on ArgumentParser.md so that it is more discoverable by users.
N/A
N/A
=> Add a link to ExperimentalFeatures.md

.gitignore, README.md, Sources/ArgumentParser/Documentation.docc/Articles/ExperimentalFeatures.md, Sources/ArgumentParser/Documentation.docc/Articles/ManualParsing.md
This includes some revisions to a few articles, and adds links to the documentation to the README.
=> Add links to the docs to the README

Examples/repeat/Repeat.swift, Package@swift-5.6.swift, Sources/ArgumentParser/Documentation.docc/Interactivity.md, Sources/ArgumentParser/Parsable Types/AsyncParsableCommand.swift, Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Parsable Types/ParsableCommand.swift, Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Parsing/InputOrigin.swift, Sources/ArgumentParser/Parsing/Interactive.swift, Sources/ArgumentParserTestHelpers/TestHelpers.swift, Tests/ArgumentParserInteractiveTests/ArgumentInteractiveTests.swift, Tests/ArgumentParserInteractiveTests/InteractiveExampleTests.swift, Tests/ArgumentParserInteractiveTests/InteractiveTests.swift
=> [GSoC] Partial initialization for ParsableCommand

Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Parsing/Interactive.swift, Tests/ArgumentParserInteractiveTests/InvalidValuesInteractiveTest.swift
=> [GSoC] Asking to retype invalid values

Sources/ArgumentParser/Parsing/Interactive.swift, Tests/ArgumentParserEndToEndTests/OptionalEndToEndTests.swift, Tests/ArgumentParserInteractiveTests/OptionInteractiveTests.swift
=> [GSoC] Conversation for required @Option

Sources/ArgumentParser/Parsing/Interactive.swift, Tests/ArgumentParserInteractiveTests/ArgumentInteractiveTests.swift, Tests/ArgumentParserInteractiveTests/FlagInteractiveTests.swift
=> [GSoC] Conversation for required @Flag

Sources/ArgumentParser/DialogBuilder/Ask.swift, Sources/ArgumentParser/DialogBuilder/Check.swift, Sources/ArgumentParser/DialogBuilder/Choose.swift, Sources/ArgumentParser/Parsing/Interactive.swift
=> [GSoC] Dialog builder for interactive mode

README.md
=> Revert README code sample to latest release

.gitignore, Sources/ArgumentParser/Parsable Types/ExpressibleByArgument.swift
=> Fix error in ExpressibleByArgument docs

Sources/ArgumentParserTestHelpers/TestHelpers.swift
Updates string diff printer to fix an OOB indexing bug.
=> Fix crash in string diff printer

CHANGELOG.md
=> Fix typo in the CHANGELOG file

Tools/generate-manual/Extensions/Process+SimpleAPI.swift, Tools/generate-manual/GenerateManual.swift
Adds a human readable description to `GenerateManualError` and updates the non-zero exit code error to include stderr to aid debugging.
Fixes: #653
=> Improve generate-manual error descriptions

Package.swift, Package@swift-5.8.swift
Prevent unhandled file build warnings.
Resolve #717
=> Prevent unhandled file build warnings
