apple/swift-argument-parser

README.md
I've checked on both SPM master and the swift-5.2 branch: 
it seems that the `Package.Dependency.Requirement` name is always [`.upToNextMinor(..)`](https://github.com/apple/swift-package-manager/blob/f2318da4f96b0607ade27eff51558206f57c2f98/Sources/PackageDescription/PackageRequirement.swift#L95).
=> Fix readme requirement name

Documentation/01 Getting Started.md, Documentation/02 Arguments, Options, and Flags.md, Documentation/03 Commands and Subcommands.md, Documentation/04 Customizing Help.md, README.md
Also fixed some typos in the documentation
\<reverted> ~Also fixed protocol conformance part in README example because that surprised me that we declared conformance on type declaration but without implementing the conformance, and only implementing the conformance in extension later… which at least I thought would not compile… but now @harlanhaskins  made me doubt it was invalid 🤔)~ \</reverted>
=> Add link to more documentation in README

.xcodesamplecode.plist
Same contents as my [merged PR into swift-standard-library-preview
](https://github.com/apple/swift-standard-library-preview/pull/1), [merged PR into swift-crypto](https://github.com/apple/swift-crypto/pull/11) and my [merged PR into swift-numerics](https://github.com/apple/swift-numerics/pull/34), giving proper markdown rendering inside Xcode.
As seen in [Apple's ARKit demo (inside `/ARKitExample.xcodeproj/` directory)](https://developer.apple.com/sample-code/wwdc/2017/PlacingObjects.zip)
Reading of markdown becomes easier. Extra important in Swift packages, where the `README` is the first file opened by Xcode when opening said package.
Just adding the `.xcodesamplecode.plist` file (to the root).
This effectively disables editing markdown files from Xcode - or at least I have not found a …
=> Adding `.xcodesamplecode.plist` to give proper markdown rending inside Xcode

Documentation/03 Commands and Subcommands.md
I added parentheses after `@OptionGroup` on  `03 Commands and Subcommands.md`.
I faced compile error when I use `@OptionGroup` property wrapper. Eventually the reason was missing parentheses. 
We don't need to fix the living [example code](https://github.com/apple/swift-argument-parser/blob/f6ac7b8118ff5d1bc0faee7f37bf6f8fd8f95602/Examples/math/main.swift#L54), it works well.
=> add parentheses after `@OptionGroup`

Sources/ArgumentParser/Usage/HelpGenerator.swift, Tests/PackageManagerTests/HelpTests.swift, Tests/UnitTests/HelpGenerationTests.swift
When generating help text, remove non-existent segments prior to joining
with an empty space. This ensures vertical visual alignment when
description for default value is the only segment.
Closes #27
=> Remove extra space leading default value help text

Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift
Should also get it working for the BSDs, Haiku, etc., as long as they have a working Swift toolchain. Tested with the Swift 5.1.4 package for Android, termux/termux-packages#4895, all 230 tests pass with the following commands:
```
swift build -j 5 --enable-test-discovery
swift test -j 5 --parallel --num-workers 3 --enable-test-discovery
```
Note the space required after `-j`, hopefully this library doesn't have the same problem.
=> Port to Android

Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Usage/MessageInfo.swift
sysexits(3) documents the "preferable exit codes for programs". It defines
```
EX_USAGE (64)         The command was used incorrectly, e.g., with the
wrong number of arguments, a bad flag, a bad syntax
in a parameter, or whatever.
```
So it seems to be a good choice for this use case.
=> Use EX_USAGE instead of EXIT_FAILURE for validation errors

Sources/ArgumentParser/Usage/HelpGenerator.swift, Tests/UnitTests/HelpGenerationTests.swift
HelpGenerator currently filters out the default values for Bools. Fixes #16 
(replaces #20 which I can't reopen)
=> Show default values for Bool properties in help

Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Sources/ArgumentParser/Utilities/StringExtensions.swift, Tests/UnitTests/ErrorMessageTests.swift, Tests/UnitTests/StringEditDistanceTests.swift
When an unknown option is encountered use levenshtein to find the closest matching option. Simply prints the error if there is no close match ([distance >= 7](https://github.com/git/git/blob/228f53135a4a41a37b6be8e4d6e2b6153db4a8ed/help.c#L592)).
Fixes #2
=> Provide suggestions for unknown options

Documentation/06 Manual Parsing and Testing.md
`ParsableCommand.parseAsRoot()` drops the first item from `CommandLine.arguments` when it receives a `nil` array as a parameter, so it is necessary to do the same before pre-processing arguments to feed to any `ParsableCommand`.
=> Fix a code example

Documentation/04 Customizing Help.md
fix typo in code example to configure the help flags.
=> typo fix in "04 Customizing Help.md"

Sources/ArgumentParser/Parsing/Name.swift, Sources/ArgumentParser/Parsing/ParsedValues.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift
This removes two types of redundant code:
- `internal` annotations (because they are the default)
- code that the compiler can synthesize, like memberwise initializers and `Equatable` conformances
Some `public init`s were removed, but those couldn't be accessed anyway, because they were nested in `internal` types - I've [complained](https://forums.swift.org/t/members-in-type-more-accessible-than-the-type-itself/24756) about the possibility of doing this before on the forums.
=> Remove code that can be synthesized

Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift
This adjusts the imports to enable building for Windows.
The major change here is that `_terminalHeight` and `_terminalWidth`
have been merged into a `_terminalSize` which returns a tuple of the
width and the height.  This is then implemented for Windows as well.
=> port to Windows

CMakeLists.txt, Examples/CMakeLists.txt, Examples/math/CMakeLists.txt, Examples/repeat/CMakeLists.txt, Examples/roll/CMakeLists.txt, Sources/ArgumentParser/CMakeLists.txt, Sources/CMakeLists.txt, Sources/TestHelpers/CMakeLists.txt, Tests/CMakeLists.txt, Tests/EndToEndTests/CMakeLists.txt, Tests/PackageManagerTests/CMakeLists.txt, Tests/UnitTests/CMakeLists.txt
Since swift-package-manager doesn't work on Windows yet, add a CMake
based build system.
=> build: add a CMake based build for Windows

Sources/ArgumentParser/Usage/HelpGenerator.swift, Tests/UnitTests/HelpGenerationTests.swift
Previously, if one defined an option thusly:
```
@Option(name: .long, default: "", help: "help text")
var option: String
```
the corresponding line of help output would be:
```
--option <option>       help text (default: )
```
After this patch, the output becomes:
```
--option <option>       help text
```
This did not affect the tests.
=> treat empty default strings and nil default strings the same way in help output

Sources/ArgumentParser/Parsing/InputOrigin.swift, Sources/ArgumentParser/Parsing/SplitArguments.swift
This removes unused code from `InputOrigin` and replaces the lone `static func` with an `init` to better match the rest of the file.
=> Clean up InputOrigin

Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsing/InputOrigin.swift, Sources/ArgumentParser/Parsing/ParserError.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Tests/UnitTests/ErrorMessageTests.swift
This is an attempt to fix https://github.com/apple/swift-argument-parser/issues/49
Questions about this proposed fix:
- Would it be better to simply extract the strings at the point where the error is thrown?
I touched every place where "duplicateExclusiveValues" appears, so it's not clear that error case would have another use than this one.
- Is the proposed replacement message any good?
=> Pass information to ParserError in order to show user a better error message

Documentation/05 Validation and Errors.md, Examples/math/main.swift, Sources/ArgumentParser/CMakeLists.txt, Sources/ArgumentParser/Parsable Properties/Errors.swift, Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Usage/MessageInfo.swift, Sources/TestHelpers/TestHelpers.swift, Tests/EndToEndTests/ValidationEndToEndTests.swift, Tests/ExampleTests/MathExampleTests.swift, Tests/ExampleTests/RepeatExampleTests.swift, Tests/ExampleTests/RollDiceExampleTests.swift
This adds an `ExitCode` error type that stores an exit code, and updates the exit machinery (1) to use `ExitCode` as the source for exit codes, and (2) to silently exit when the provided error is an `ExitCode` instance.
New API:
```swift
/// An error type that only includes an exit code.
///
/// If you're printing custom errors messages yourself, you can throw this error
/// to specify the exit code without adding any additional output to standard
/// out or standard error.
public struct ExitCode: Error {
/// Creates a new `ExitCode` with the given code.
public init(_ code: Int32)
/// An exit code that indicates successful completion of a command.
public static let success
/// An exit code that indicates that the command failed.
public static let failure
/// An exit code that indicates …
```
=> Add support for exiting without printing an error

Sources/ArgumentParser/Parsable Properties/Flag.swift, Tests/EndToEndTests/FlagsEndToEndTests.swift
Per [discussion][], add an initializer for `Flag<Optional<Bool>>` that
allows the default value to be `nil`, enabling capacity to distinguish
the lack of a supplied flag vs the default value from user.
[discussion]: https://forums.swift.org/t/flag-default-value-where-did-it-come-from/34204/10
Newly added initializer enables the following `Flag` declaration.
```swift
@Flag(inversion: .prefixedNo)
var throwingAwayMyShot: Bool?
```
When neither `--no-throwing-away-my-shot` nor `--throwing-away-my-shot` is supplied as command-line argument in this scenario, this flag value is `nil`. Otherwise it has same behavior as the non-optional variant.
This is variant of the existing `Flag<Bool>` flag. Current documentation does not explicitly point out this new API. It may be reasonable to expect user …
=> Add @Flag initializer for Optional<Bool>

Sources/ArgumentParser/Usage/HelpGenerator.swift, Tests/UnitTests/HelpGenerationTests.swift
The original logic assumed that flags would only be grouped in pairs.
Fixes https://github.com/apple/swift-argument-parser/issues/50
Still an issue: with a `@Flag` value typed as a `CaseIterable` enum, its default value doesn't appear. The latter is a new issue https://github.com/apple/swift-argument-parser/issues/56
=> Fix for help output of groups of flags

Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Tests/EndToEndTests/FlagsEndToEndTests.swift, Tests/UnitTests/ErrorMessageTests.swift
Constructors for Bool Flags with inverted pairs do not have a `FlagExclusivity` parameter (https://github.com/apple/swift-argument-parser/issues/60). This PR adds a `FlagExclusivity` parameter to two of the Flag constructors.
On `Flag`,
```
public init(name: NameSpecification = .long, default initial: Bool? = false,
inversion: FlagInversion, help: ArgumentHelp? = nil)
```
becomes
```
public init(name: NameSpecification = .long, default initial: Bool? = false,
inversion: FlagInversion, exclusivity: FlagExclusivity = .chooseLast,
help: ArgumentHelp? = nil)
```
In the process, the logic to handle flag exclusivity collision was refactored to a new static function on `ArgumentSet`, and is used for `Bool` flags with inversions as well as flags built from `CaseIterable` enums.
The new parameter …
=> add control of exclusivity for Bool Flags when inversion is enabled

Sources/ArgumentParser/Parsing/ArgumentSet.swift, Tests/EndToEndTests/FlagsEndToEndTests.swift
Previously, using a set of flags declared with FlagExclusivity.chooseFirst would result in an error instead of choosing the first from the command line. (See https://github.com/apple/swift-argument-parser/issues/66).
Added a case handling repeating arguments in the `ArgumentSet.updateFlag` function.
The previous behaviour had the repeating-arguments-with-.chooseFirst situation going through the `default` case, which didn't add the current argument to the list of used arguments, which later caused an error due to the argument being incorrectly deemed to have not been used.
No change to documentation is needed.
Tests added to `FlagsEndToEndTests.testParsing_invert` and `FlagsEndToEndTests.testParsingCaseIterable_RepeatableFlags`.
None.
This PR fixes …
=> make FlagExclusivity.chooseFirst work

Sources/ArgumentParser/Usage/HelpGenerator.swift, Tests/EndToEndTests/SubcommandEndToEndTests.swift
When using option groups to bring options into subcommands that are also
used in parent commands, the help system duplicates the options in the
generated output.
For instance, in the `SubcommandEndToEndTest` example, the `--name`
argument is listed twice for both the subcommands `CommandA` and
`CommandB`, and expected by the test assertion.
It is annoying in a simple case like this but causes a lot of unhelpful
noise in help output when you share more and more options across a
command heirarchy.
To solve this we need to keep track of what
`HelpGenerator.Section.Element` values have already been processed from
parent commands in the command stack. I acheived this by making
`Element` conform to `Hashable` to track in a `Set`.
This assumes that we don't need to support re-using command names …
=> Fix duplicate options showing up in command help output

Examples/CMakeLists.txt, Examples/math/CMakeLists.txt, Examples/repeat/CMakeLists.txt, Examples/roll/CMakeLists.txt, Sources/ArgumentParser/CMakeLists.txt, Sources/CMakeLists.txt, Sources/SAPTestHelpers/CMakeLists.txt, Tests/EndToEndTests/CMakeLists.txt, Tests/UnitTests/CMakeLists.txt
=> CMake adjustments

Documentation/02 Arguments, Options, and Flags.md, Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Parsing/SplitArguments.swift, Tests/EndToEndTests/RepeatingEndToEndTests.swift
We don't currently have a way for `@Argument` arrays to capture command-line inputs that look like options. This capability is important for tools like SwiftPM that need to forward input to another command.
For example, the `swift-run` command needs to be able to parse all three of the arguments here into an array, including `--count`:
```
% swift run repeat --count 5 hello
``` 
This introduces an `ArgumentArrayParsingStrategy` enum with a `remaining` case that  matches the current behavior, as well as an `unconditionalRemaining` case that captures all remaining input.
```swift
/// The strategy to use when parsing multiple values from `@Option` arguments
/// into an array.
public enum ArgumentArrayParsingStrategy {
/// Parse only unprefixed values from the command-line input, ignoring
/// …
```
=> Add a catch-all argument parsing strategy

Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Tests/ArgumentParserEndToEndTests/FlagsEndToEndTests.swift
Stop failing upon seeing a repeated value from a mutually-exclusive set of flags.
This adds an `Equatable` requirement to the `Flag` constructors from `CaseIterable` enums. Given the other requirements on those enums, `Equatable` conformance is automatic and therefore costs nothing.
The switch statement in `ArgumentSet.updateFlag` is also much simplified, by calling `values.element(forKey:)` only when it is needed.
This fixes https://github.com/apple/swift-argument-parser/issues/59
This supersedes https://github.com/apple/swift-argument-parser/pull/70
=> Repeated flags fix

Documentation/02 Arguments, Options, and Flags.md, Sources/ArgumentParser/Parsable Properties/Argument.swift, Tests/ArgumentParserEndToEndTests/DefaultsEndToEndTests.swift, Tests/ArgumentParserUnitTests/UsageGenerationTests.swift
I added support default value for `@Argument` property wrapper.
Related issue is #64. and Swift Forums thread is [`Default Argument values?  - Related Projects / ArgumentParser`](https://forums.swift.org/t/default-argument-values/34174)
The way to implement is same as `@Option` property wrapper. Just add a optional `default` parameter on its `init` method and default value is nil. `ArgumentSet` and` ArgumentDefinition` do all the work in the `init` method.
> How has the new feature been documented? 
I added documents on methods I changed.
> Have the relevant portions of the guide been updated in addition to symbol-level documentation?
I fixed a bit talking about `default` parameter on `02 Arguments, Options, and Flags.md`.
> How is the new feature tested?
I added tests similar to the …
=> Add support for default Argument value

Sources/ArgumentParser/Parsable Properties/OptionGroup.swift, Sources/ArgumentParser/Parsing/ArgumentDecoder.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Tests/ArgumentParserEndToEndTests/NestedCommandEndToEndTests.swift
Previously, we were only storing full-decoded ParsableCommand instances for subcommands to pick up with the @OptionGroup() wrapper. This change stores all decoded @OptionGroup() values as well, so that they can be shared from super- to subcommand.
In this example from the test, the `Sub` command would never actually see a value in its `options.name` property, since the `--name Tom` inputs get consumed the first time that `Options` is decoded:
```swift
struct Options: ParsableArguments {
@Option() var name: String?
}
struct Super: ParsableCommand {
static let configuration = CommandConfiguration(subcommands: [Sub.self])
@OptionGroup() var options: Options
struct Sub: ParsableCommand {
@OptionGroup() var options: Options
}
}
```
=> Fix ParsableArguments sharing between cmds & subcommands

Sources/ArgumentParser/Usage/HelpCommand.swift
Currently `HelpCommand` is launching a side-effect in `run` method (printing in the console the help). This PR fixes it and throw the effect to the next layer, who will catch it and treat the effect properly. Effects should be handled on the `main` method inside `exit(withError:)` or **let to the user decided how to manage them**
This change will let us write something like:
```swift
enum ParsableCommandError: Error {
case general(String)
}
extension ParsableCommand {
func parse(_ arguments: [String]? = nil) -> Result<ParsableCommand, ParsableCommandError> {
do {
let command = try Self.parseAsRoot(arguments)
try command.run()
return .success(command)
} catch {
let info = Self.fullMessage(for: error)
return .failure(.general(info))
}
}
}
```
In the end, delegate the responsibility about …
=> Remove side-effects in HelpCommand

Sources/ArgumentParser/Parsable Properties/Option.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift, Tests/ArgumentParserUnitTests/UsageGenerationTests.swift
I fixed a bug #76. The cause of the bug was that the option of `ArgumentDefinition.Help` was not correctly given only for `init(name:, default:, parsing:, help:, transform:)`.
I added tests HelpGenerationTests and UsageGenerationTests.
=> Fix optional argument is listed as mandatory

Sources/ArgumentParser/Usage/HelpGenerator.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
When there's a subcommand with a long name and empty abstract, the help is generated with an extra new line below the command name.
For example:
```
USAGE: h <subcommand>
OPTIONS:
-h, --help              Show help information.
SUBCOMMANDS:
command-a
command-with-very-long-name
short-command           Test short command name.
```
This patch removes the extra new line in help.
```
USAGE: h <subcommand>
OPTIONS:
-h, --help              Show help information.
SUBCOMMANDS:
command-a
command-with-very-long-name
short-command           Test short command name.
```
=> Improve help generation when command abstract is empty

Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Parsing/SplitArguments.swift, Tests/ArgumentParserEndToEndTests/RepeatingEndToEndTests.swift
Because of the way we split out single-dash arguments into both the whole string and each individual character, we were capturing single-dash arguments multiple times. This fixes #88.
=> Don't repeat single-dash arguments with unconditionalRemaining arrays

Sources/ArgumentParser/Parsable Properties/Errors.swift, Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Usage/MessageInfo.swift, Sources/ArgumentParserTestHelpers/TestHelpers.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift, Tests/ArgumentParserExampleTests/RepeatExampleTests.swift, Tests/ArgumentParserExampleTests/RollDiceExampleTests.swift, Tests/ArgumentParserUnitTests/ExitCodeTests.swift
This provides a method on all `ParsableArguments`/`ParsableCommand` types that lets you retrieve the exit code associated with an error.
1) Add an `exitCode(for:)` method that converts an error to an `ExitCode` instance. 
```swift
extension ParsableArguments {
/// Returns the exit code for the given error.
///
/// - Parameter error: An error to generate a message for.
/// - Returns: The exit code for the `error`.
public static func exitCode(for error: Error) -> ExitCode
}
```
2) Upgrade the `ExitCode` type to be a bit more useful, making it `RawRepresentable` and  `Hashable`. The represented code is now available through the `rawValue` property.
I included symbol documentation for the new APIs.
I added unit tests for the `exitCode(for)` method and converted the integration test helper to …
=> Add an API for converting an error to an exit code

Sources/ArgumentParser/Parsing/CommandParser.swift, Tests/ArgumentParserEndToEndTests/DefaultSubcommandEndToEndTests.swift, Tests/ArgumentParserEndToEndTests/NestedCommandEndToEndTests.swift
We were incorrectly skipping over dash-prefixed inputs when looking for the next
subcommand. This means that input like `command sub1 --foo sub2` would match the
sub1 and sub2 subcommands, even if `--foo` wasn't defined by sub1. This manifested
in issues where a value expected by `--foo` would be eaten by the subcommand matcher.
Note that this changes a couple test fixtures where we were incorrectly specifying inputs.
Fixes #92.
=> Enforce that options must be used by command before matching a subcommand

Sources/ArgumentParser/Parsable Types/ExpressibleByArgument.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
This PR fixes #87.
Simply we can add `defaultValueDescription` in `ExpressibleByArgument` protocol
```
/// A type that can be expressed as a command-line argument.
public protocol ExpressibleByArgument {
/// Creates a new instance of this type from a command-line-specified
/// argument.
init?(argument: String)
/// Add this ↓
var defaultValueDescription: String { get }
}
```
Default behavior is given by default implementation declared in `ExpressibleByArgument` as Protocol Extensions.  Only users who want to customize need to override `defaultValueDescription`.
[How can I change the default value string displayed in Help? \- Related Projects / ArgumentParser \- Swift Forums](https://forums.swift.org/t/how-can-i-change-the-default-value-string-displayed-in-help/34527/3)
=> Add support for customizing default value string displayed in Help (#87)

Sources/ArgumentParser/Parsable Types/ParsableArgumentsValidation.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Tests/ArgumentParserUnitTests/CMakeLists.txt, Tests/ArgumentParserUnitTests/ParsableArgumentsValidationTests.swift
Continue restructuring the `ParsableArguments` validation layer. (Previous discussions: #91)
- Move the "positional argument following an array of positional arguments" check to a new struct `PositionalArgumentsValidator`.
- Make `ParsableArguments._validation` throw a combination of validation errors, and add the proper error description.
- Add tests for `PositionalArgumentsValidator`
So a `ParsableArguments` with both coding key error and positional arguments error is now reported in the following form:
```
Fatal error: Validation failed for `Repeat`:
- Can't have a positional argument `phrase` following an array of positional arguments `items`.
- Arguments `includeCounter`,`items` are defined without corresponding `CodingKey`s.
: file …
```
=> Add `PositionalArgumentsValidator`

Examples/math/main.swift, Sources/ArgumentParser/Parsable Types/CommandConfiguration.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Parsing/ParserError.swift, Sources/ArgumentParser/Usage/HelpCommand.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParser/Usage/MessageInfo.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Tests/ArgumentParserEndToEndTests/SubcommandEndToEndTests.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift, Tests/ArgumentParserExampleTests/RepeatExampleTests.swift, Tests/ArgumentParserUnitTests/ExitCodeTests.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
Adds built-in support for responding to a `--version` flag. This flag is only valid when a command provides a `version:` parameter in its configuration. Fixes #25.
If a command in the tree has specified a version, the `--version` flag is checked for only after evaluating any explicitly defined arguments. This allows commands to define their own `--version` flags or options and not have them be overridden by the auto-generated version.
Nested commands inherit their version from their parent commands, and can override their parent by providing their own version string.
`version` is added to the `CommandConfiguration` type and to the initializer:
```swift
/// Creates the configuration for a command.
///
/// - Parameters:
///   - commandName: The name of the command to use on the command …
```
=> Add built-in support for --version flag

Sources/ArgumentParser/Parsable Types/ParsableCommand.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Tests/ArgumentParserEndToEndTests/SubcommandEndToEndTests.swift
This change calls validate on every ParsableCommand in the command stack, instead of just the leaf command to fix issue #103
=> Call validate on the entire command stack

README.md
The ArgumentParser dependency should be specified using the `target` block, not `product`.
=> Changed Readme notes about the ArgumentParser integration via SwiftPM

Sources/ArgumentParser/Parsable Types/ParsableArgumentsValidation.swift, Tests/ArgumentParserUnitTests/ParsableArgumentsValidationTests.swift
Adds `ParsableArgumentsUniqueNamesValidator`, which conforms to `ParsableArgumentsValidator` and implements the validation requested in https://github.com/apple/swift-argument-parser/issues/112: ensuring that argument names aren't duplicated in a type conforming to `ParsableArguments` or `ParsableCommand`.
Custom names can be used to give two or more options or flags the same name. For example:
```swift
import ArgumentParser
struct TwoOfTheSameName: ParsableCommand {
@Option()
var foo: String
@Option(name: .customLong("foo"))
var notActuallyFoo: String
func run() throws {
print("foo: \(foo)")
print("notActuallyFoo: \(notActuallyFoo)")
}
}
TwoOfTheSameName.main(["--foo thing"])
```
gives this output in `master`:
```
Error: Missing expected argument '--foo <foo>'
Usage: two-of-the-same-name …
```
=> Unique argument names validator

Sources/ArgumentParser/Parsable Properties/Errors.swift
Windows does not have a `EX_USAGE`, use `ERROR_BAD_ARGUMENTS` instead.
=> ArgumentParser: repair the build on Windows

Sources/ArgumentParser/Parsable Properties/Errors.swift
This is a very short PR that came out of some changes made in #115. Because it is an API change is was suggested this become a PR in its own right.
However, looking at the code I wanted to make sure the motivations are correct and consider some alternatives. 
`ValidationError` conforms to `CustomStringConvertible`, `description` is `public` and it vends `message`. So client code can read the `message` value without this change.
Remove `message` value entirely and use `description`.
```swift
public struct ValidationError: Error, CustomStringConvertible {
public internal(set) var description: String
/// Creates a new validation error with the given message.
public init(_ message: String) {
self.description = message
}
}
```
`message` should be `private(set)`. No library code (currently) …
=> Changing the access level of `ValidationError.message`

Documentation/02 Arguments, Options, and Flags.md, Sources/ArgumentParser/Parsable Properties/ArgumentHelp.swift, Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsable Properties/Option.swift, Sources/ArgumentParser/Parsable Types/EnumerableFlag.swift, Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Tests/ArgumentParserEndToEndTests/FlagsEndToEndTests.swift
This addresses the need for providing name specifications for `enum` flags, since property wrappers can't be used for enumeration cases.
This includes a new `EnumerableFlag` protocol:
```swift
/// A type that represents the different possible flags to be used by a
/// `@Flag` property.
public protocol EnumerableFlag: CaseIterable {
/// Returns the name specification to use for the given flag.
static func name(for value: Self) -> NameSpecification
/// Returns the help information to show for the given flag.
static func help(for value: Self) -> ArgumentHelp?
}
```
As well as new `EnumerableFlag`-constrained `@Flag` initializers that replace the current ones that are constrained to `String`/`CaseIterable`.
Wrote type- and symbol-level documentation for `EnumerableFlag`, revised docs for the …
=> Add an EnumerableFlag protocol

CMakeLists.txt, Sources/CMakeLists.txt, cmake/modules/ArgumentParserConfig.cmake.in, cmake/modules/CMakeLists.txt
This is a fairly early attempt at integrating this repo into the SwiftPM bootstrapped build, someone better at CMake than I am should probably review :)
=> Add support to CMake to build swift-argument-parser during SwiftPM bootstrapping

Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Parsing/ParserError.swift, Sources/ArgumentParser/Usage/MessageInfo.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Tests/ArgumentParserEndToEndTests/ValidationEndToEndTests.swift, Tests/ArgumentParserExampleTests/RepeatExampleTests.swift
This implements the feature mentioned in #134. I think it would also remove the need for #135.
When a `ParserError` is thrown, check to see if there are zero arguments. If so, the error is wrapped in the new `.noArguments` case, which allows the original error to be reported, while also triggering the full help message instead of usage.
If there's a Swiftier/more concise way of writing the addition to MessageInfo.swift, I'd love to know.
I wasn't sure whether this needs explicit mention in the documentation, and if so, which section to add it to.
=> Display help when no arguments results in error

Sources/ArgumentParser/Parsing/SplitArguments.swift, Tests/ArgumentParserEndToEndTests/EqualsEndToEndTests.swift
This fixes #132, by letting you separate a short option and its value with an equals sign.
The new tests are in EqualsEndToEndTests.swift for now, but arguably they belong in ShortNameEndToEndTests.swift. I can move them if necessary. I also omitted new tests for long argument names with equals sign, as that seems to be tested elsewhere.
I don't think there needs to be any further documentation, as this was already the documented behavior.
=> Fix short names with equals sign

Documentation/04 Customizing Help.md, Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Parsable Types/ParsableCommand.swift, Sources/ArgumentParser/Usage/HelpCommand.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParser/Usage/MessageInfo.swift, Sources/ArgumentParserTestHelpers/TestHelpers.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
This adds two methods for generating the help screen for a command or subcommand.
The additions includes two methods, one on `ParsableArguments` and one on `ParsableCommand`. The second method has a `subcommand` parameter, and is called on the root command to generate the help text for a subcommand:
```swift
let help = RootCommand.helpMessage(for: Subcommand.self)
```
The two new methods:
```swift
extension ParsableArguments {
/// Returns the text of the help screen for this type.
public static func helpMessage(columns: Int? = nil) -> String
}
extension ParsableCommand {
/// Returns the text of the help screen for the given subcommand of this
/// command.
public static func helpMessage(
for subcommand: ParsableCommand.Type,
columns: Int? = nil
) -> String
}
```
Documentation is included …
=> Add APIs for generating the help screen

Sources/ArgumentParser/Parsable Properties/Option.swift, Tests/ArgumentParserUnitTests/UsageGenerationTests.swift
Documentation for `Option.init(... transform:)` says: "If the property has an `Optional` type, or you provide a non-`nil` value for the `initial` parameter, specifying this option is not required."
Initializer works exactly this way but provides wrong synopsis for `Optional` type properties.
=> Set isOptional flag for options of Optional type

Sources/ArgumentParser/Utilities/StringExtensions.swift, Tests/ArgumentParserUnitTests/StringWrappingTests.swift
Every lines in option's discussion must be properly indented, even the short ones.
=> Fix invalid indentation of strings with short lines

Sources/ArgumentParser/Usage/HelpGenerator.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
In the event a configuration has an empty abstract and non-empty discussion,
an extra line was generated. This patch removes that line.
ISSUE: SAP-156 https://github.com/apple/swift-argument-parser/issues/156
- [x ] I've added at least one test that validates that my change is working, if appropriate
- [x ] I've followed the code style of the rest of the project
- [x ] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x ] I've updated the documentation if necessary
=> Remove extraneous newline for empty abstract

Documentation/02 Arguments, Options, and Flags.md, Documentation/03 Commands and Subcommands.md, Documentation/05 Validation and Errors.md, README.md, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParser/Usage/MessageInfo.swift, Tests/ArgumentParserEndToEndTests/SubcommandEndToEndTests.swift, Tests/ArgumentParserEndToEndTests/TransformEndToEndTests.swift, Tests/ArgumentParserEndToEndTests/ValidationEndToEndTests.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift, Tests/ArgumentParserExampleTests/RepeatExampleTests.swift, Tests/ArgumentParserExampleTests/RollDiceExampleTests.swift, Tests/ArgumentParserPackageManagerTests/HelpTests.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
This adds some new messages to error and help output that guide users to find more information.
Validation errors now include a message about using `--help`:
```
$ roll --bad-flag
Error: Unknown option '--bad-flag'
Usage: roll [--times <n>] [--sides <m>] [--seed <seed>] [--verbose]
See 'roll --help' for more information.
```
The help screen now shows a message about the implicit `help` subcommand when the help screen contains subcommands:
```
$ math --help
OVERVIEW: A utility for performing maths.
USAGE: math <subcommand>
OPTIONS:
--version               Show the version.
-h, --help              Show help information.
SUBCOMMANDS:
add                     Print the sum of the values.
multiply                Print the product of the values.
stats                   Calculate descriptive …
```
=> Additional help messages

Sources/ArgumentParser/Parsing/CommandParser.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
When argument is an array and no input is given but “-h”, if you throw an Error in Validate function, it prints error and short usage instead of help message.
'command -h'
This patch checks built-in flags before throwing a validation error.
Solves #149
=> Fix showing help message when “-h” is given as an input for an array (#149)

Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Parsing/SplitArguments.swift, Tests/ArgumentParserEndToEndTests/OptionGroupEndToEndTests.swift, Tests/ArgumentParserEndToEndTests/RepeatingEndToEndTests.swift
This fixes #130 by (1) not consuming the `--` terminator while parsing, and (2) ignoring the terminator when checking to see that all the arguments have been used.
=> Don't consume the terminator during parsing.

Sources/ArgumentParser/Parsable Types/ParsableCommand.swift
This brings the `main()` method in line with using the new `@main` attribute on the root
command type.
The changes here are to make `ParsableCommand.main()` a `Void`-returning function, to break out a separate no-argument version, and to remove the default parameter. The default-argument version doesn't satisfy the `() -> Void` requirement for `@main`.
The `main()` method now returns without exiting on successful execution of a 
No real impact. Documentation for using `@main` with the library to follow.
All existing tests continue to pass. SwiftPM will need an update to support `@main` in executable targets.
Typical code should continue to behave as expected, but this is source-breaking if anyone has a strongly-typed usage of `ParsableCommand.main()`, e.g. `let mainFunction: ([String]?) …
=> Remove `Never` return from ParsableCommand.main()

Sources/ArgumentParserTestHelpers/TestHelpers.swift, Tests/ArgumentParserEndToEndTests/FlagsEndToEndTests.swift, Tests/ArgumentParserEndToEndTests/SourceCompatEndToEndTests.swift, Tests/ArgumentParserUnitTests/NameSpecificationTests.swift, Tests/ArgumentParserUnitTests/ParsableArgumentsValidationTests.swift, Tests/ArgumentParserUnitTests/SplitArgumentTests.swift
NFC. This adds compilation tests for all the property wrappers, including all the various permutations of their default parameter values.
=> Test source compatibility for property wrappers

Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsable Properties/Option.swift, Sources/ArgumentParser/Parsable Types/ExpressibleByArgument.swift, Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Tests/ArgumentParserEndToEndTests/SourceCompatEndToEndTests.swift
This drops the `ExpressibleByArgument` conformance for `Optional`. This conformance doesn't quite make sense, and allowed property declarations like this:
```swift
@Option(default: 0) var count: Int?
```
The default value meant that `count` would never be `nil`, and therefore shouldn't be optional.
This change adds initializers specifically for when an `Option`'s or `Argument`'s value is optional, without a `default` parameter as well as deprecated versions that include a `default` parameter to guide clients to the correct declaration syntax.
The new initializers are documented; related initializers have been updated. There is no change required in the guides.
Existing tests exercise the functionality and verify the largely source-compatible nature of the change.
While this is technically …
=> Remove `ExpressibleByArgument` conformance from `Optional`

Documentation/01 Getting Started.md, Documentation/02 Arguments, Options, and Flags.md, Documentation/03 Commands and Subcommands.md, Documentation/04 Customizing Help.md, Documentation/05 Validation and Errors.md, Documentation/06 Manual Parsing and Testing.md, Examples/math/main.swift, Examples/repeat/main.swift, README.md, Sources/ArgumentParser/Parsable Types/EnumerableFlag.swift, Sources/ArgumentParser/Parsable Types/ParsableCommand.swift, Sources/ArgumentParser/Usage/HelpCommand.swift, Sources/ArgumentParserTestHelpers/TestHelpers.swift, Tests/ArgumentParserEndToEndTests/RepeatingEndToEndTests.swift, Tests/ArgumentParserEndToEndTests/SubcommandEndToEndTests.swift, Tests/ArgumentParserPackageManagerTests/PackageManager/GenerateXcodeProject.swift, Tests/ArgumentParserUnitTests/ParsableArgumentsValidationTests.swift, Tools/changelog-authors/main.swift
This changes `ParsableCommand`'s `run` requirement to be mutating. This allows for things like in-place sorting or filtering of arguments without making a mutable copy.
This change supersedes #33.
The only change here is the switch to mutating for the `run()` method.
```swift
protocol ParsableCommand: ParsableArguments {
// other requirements
/// ...
mutating func run() throws
}
```
We didn't previously mention the non-mutatingness of `run()`, so that doesn't require a change. All code samples have been updated to implement the new requirement.
All existing tests pass with the change.
~This **will require code changes** for every command that implements a `run()` method, since a non-mutating `run()` won't properly satisfy the new requirement. Since `ParsableCommand` provides a default …
=> Make ParsableCommand.run() a mutating method

Sources/ArgumentParser/CMakeLists.txt
The CMakeLists.txt was missing `Parsable Types/ParsableArgumentsValidation.swift`. This adds that file to the CMakeLists.
=> Adding missing ParsableArgumentsValidation.swift to CMakeLists.

Examples/CMakeLists.txt
The usage of `sqrt()` requires linking libm on Linux. This adds the appropriate CMake entry to allow for this.
=> Fixing math example on Linux

Sources/ArgumentParser/Parsable Properties/Flag.swift, Tests/ArgumentParserEndToEndTests/FlagsEndToEndTests.swift, Tests/ArgumentParserEndToEndTests/SourceCompatEndToEndTests.swift, Tests/ArgumentParserUnitTests/ErrorMessageTests.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift, Tests/ArgumentParserUnitTests/ParsableArgumentsValidationTests.swift
This change converts the old `@Flag` initializers for `CaseIterable`/`String` enums from deprecated to unavailable, in preparation for the 0.1.0 release.
=> Convert deprecations from pre-0.1.0 to unavailable

CHANGELOG.md, Documentation/01 Getting Started.md, README.md
This includes updating the examples of declaring the dependency, as well.
=> Update changelog for 0.1.0 release

Sources/ArgumentParser/Parsable Properties/NameSpecification.swift, Sources/ArgumentParser/Parsing/Name.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Sources/ArgumentParser/Utilities/SequenceExtensions.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift, Tests/ArgumentParserUnitTests/UsageGenerationTests.swift
SortedNames for ArgumentDefinition has been changed.
NameSpecification now uses Array type for elements.
* Usage will choose the first long name, if available, or otherwise the first short name
* Help screen will show short names, then long names, in the order of their declaration.
Solves (#167)
=> Use the first long name in usage

Sources/ArgumentParser/Usage/HelpGenerator.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
It would be useful to see default subcommand in help messages.
=> Help message for default subcommands

Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Parsing/ParsedValues.swift, Tests/ArgumentParserUnitTests/ErrorMessageTests.swift
This pushes any errors indicated by unexpected arguments after parsing out to the same late position. We were previously stopping immediately when the command is a leaf node; that isn't necessary and created an awkward second error path.
=> Show option-based errors before unexpected positional errors

Sources/ArgumentParser/Parsable Types/ParsableCommand.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Utilities/Tree.swift, Tests/ArgumentParserUnitTests/TreeTests.swift
This avoids the infinite recursion that causes a crash and shows the user a meaningful error message.
Fixes: https://github.com/apple/swift-argument-parser/issues/192
=> Add a precondition to prevent the parsing of a command that has itself as its subcommand

Sources/ArgumentParser/Utilities/SequenceExtensions.swift
Proposes a slight optimization of `uniquified ` added in #179.  Using `contains` on the temporary `sequence` variable leads to quadratic performance because `.contains` runs in O(n) time.  
By instead creating a temporary variable that is a dictionary, we can filter on `self` and use the dictionary's [`.updateValue`](https://developer.apple.com/documentation/swift/dictionary/3127179-updatevalue) member, passing in each element. This keeps performance near O(n) - the tradeoff being that this requires elements to conform to `Hashable` (vs just `Equatable`).
Not sure if another test is needed as all tests continue to pass, but happy to add one if this is smiled upon.
=> Optimize Sequence.uniquified()

Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsable Properties/Option.swift, Sources/ArgumentParser/Parsable Properties/OptionGroup.swift, Tests/ArgumentParserUnitTests/ParsableArgumentsValidationTests.swift
Fixes #206, where unless the property wrapper types were used with empty parentheses, `ParsableArguments`-conforming types would not have a no-argument initializer synthesized and thus would unexpectedbly fail to
conform to `ParsableArguments`.
This is caused by [a limitation of the compiler's property wrapper support](https://bugs.swift.org/browse/SR-13295) where it fails to see initializers in extensions as candidates for property wrapper requirements.
By declaring a no-argument intializer in each type, but then marking it as unavailable, the no-parenthesis syntax now works, but selects the existing initializers in extensions anyway.
=> Allow property wrappers to be used without parentheses

CHANGELOG.md, Documentation/01 Getting Started.md, Documentation/02 Arguments, Options, and Flags.md, Documentation/03 Commands and Subcommands.md, Documentation/05 Validation and Errors.md, Documentation/06 Manual Parsing and Testing.md, Examples/math/main.swift, Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsable Properties/Option.swift, Sources/ArgumentParser/Parsable Types/EnumerableFlag.swift, Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Usage/HelpCommand.swift
Since https://github.com/apple/swift-argument-parser/pull/207, property wrapper usage with no arguments can now use the more natural syntax without the `()`. Updates documentation and example code accordingly.
=> Update documentation and examples to use natural property wrapper syntax

Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsable Properties/Option.swift, Sources/ArgumentParser/Parsable Types/ExpressibleByArgument.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
Makes default values for `@Argument`s and `@Option`s whose values are arrays of `ExpressibleByArgument` use their elements' `defaultValueDescription` in the help text.
Fixes #208.
=> Make arrays with default values use their elements' defaultValueDescription

Documentation/07 Completion Scripts.md
Users do not familiarize with the shell-completions scripts in Zsh could be frustrated following [this guide](https://github.com/apple/swift-argument-parser/blob/280700d361c1b3af6e2345f5e24f67fa9450bec6/Documentation/07%20Completion%20Scripts.md#installing-zsh-completions). `oh-my-zsh` uses a specific filename format `_example` - I think it is useful to add this information to documentation together with an example.
=> Update doc with Zsh completion filename format

Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift, Tests/ArgumentParserUnitTests/CompletionScriptTests.swift
This PR includes some improvements to the zsh completion script generator:
* `shellCommand` stores output in a local array that is passed to `_describe` to handle spaces and other punctuation in the shell command output
* elide the help abstract if it is empty, as it confuses the zsh completion system
* set the `_<commandName>_commandname` to `$words[1]`, which is the full name of the command used to invoke the completion. This ensures invocations like `./build/debug/math ...` as passed on to the `_custom_completion` command.
The existing tests have been updated.
=> fix: Improve zsh completion script generator

Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift, Tests/ArgumentParserUnitTests/CompletionScriptTests.swift
- Escape appropriate chars in subcommand abstracts as well.
Fixes #218 and fixes #221.
Note: This changes `zshEscapingSingleQuotes()` to use `replacingOccurrencesOf()` instead of `split()`/`join()`. Let me know if that should be reverted.
=> Escape backslash and square brackets in addition to single quotes

Sources/ArgumentParser/Parsable Types/CommandConfiguration.swift, Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Usage/MessageInfo.swift
This supports SwiftPM, which uses "error:" instead of "Error:" to make its error messages match the compiler.
=> Add an experimental customization point for the error label

Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift, Tests/ArgumentParserUnitTests/CompletionScriptTests.swift
This changes the existing string substitution expression that's used to take the results of a custom completion callback and turn it into an array of strings so that each string is not split on whitespace it might contain.
I will not pretend to fully understand why this new "expand string into array" expression works when the other didn't, but it does. The new expression is based on this SO answer: https://unix.stackexchange.com/a/29748. I know just enough shell stuff to be dangerous, so it's very likely there's a better way than what I've found, and I'd be happy to get some feedback on this!
The motivation for this change was for the install command of [xcodes](https://github.com/RobotsAndPencils/xcodes) (PR with swift-argument-parser support …
=> Improve support for multi-word completion strings in ZSH

Documentation/07 Completion Scripts.md, Sources/ArgumentParser/CMakeLists.txt, Sources/ArgumentParser/Completions/CompletionsGenerator.swift, Sources/ArgumentParser/Completions/FishCompletionsGenerator.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift, Tests/ArgumentParserUnitTests/CompletionScriptTests.swift
Add fish completion script generation.
The math example app generates the following fish script (`swift run math --generate-completion-script fish`).
```
function __fish_math_using_command
set cmd (commandline -opc)
if [ (count $cmd) -eq (count $argv) ]
for i in (seq (count $argv))
if [ $cmd[$i] != $argv[$i] ]
return 1
end
end
return 0
end
return 1
end
complete -c math -n '__fish_math_using_command math' -f -a 'add' -d 'Print the sum of the values.'
complete -c math -n '__fish_math_using_command math' -f -a 'multiply' -d 'Print the product of the values.'
complete -c math -n '__fish_math_using_command math' -f -a 'stats' -d 'Calculate descriptive statistics.'
complete -c math -n '__fish_math_using_command math' -f -a 'help' -d 'Show subcommand help information.'
complete -c math -n …
```
=> Add Fish completion generator

Documentation/02 Arguments, Options, and Flags.md, Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsable Properties/Option.swift, Tests/ArgumentParserEndToEndTests/DefaultsEndToEndTests.swift
Un-deprecates (but changes the semantics of) the initializers for an array value type without a default, forcing the user to specify at least one value from the command line.
The motivation behind this is to allow users of this framework to force a user to provide at least one argument, without having to provide custom error handling. An example of a command that uses this argument setup is `cp`, which has a variant for one or more `source_file` arguments:
`cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory`
This unfortunately does un-do the deprecations done In #193 and also is a source-breaking change in a similar vein as the one in #170 (changing the semantics of the case where no default is provided) and so will need to wait for the next minor release as per …
=> Allow required array arguments, options, and flags

Sources/ArgumentParser/Parsable Types/ParsableArgumentsValidation.swift, Tests/ArgumentParserUnitTests/ParsableArgumentsValidationTests.swift
Fixes #231. Note that this changes the error text slightly, to include the single/double-dash prefix.
=> Allows single- and double-dashed args with the same name

Examples/repeat/main.swift, Sources/ArgumentParser/Parsing/ArgumentDecoder.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Parsing/ParsedValues.swift, Sources/ArgumentParser/Parsing/SplitArguments.swift, Tests/ArgumentParserEndToEndTests/ShortNameEndToEndTests.swift, Tests/ArgumentParserUnitTests/SplitArgumentTests.swift
This converts some operations to constant time when parsing individual elements, leading to big performance improvements with larger argument lists.
=> Improve parsing performance

Sources/ArgumentParser/Parsing/CommandParser.swift, Tests/ArgumentParserEndToEndTests/ValidationEndToEndTests.swift
Since #104, mutations made to a command struct by its `validate()` function are lost when using `parseAsRoot(_:)`. This is because validations are run on a mutable copy of the parsed command, and that copy is never stored.
My teammates and I use `validate()` as a place to enforce invariants. For example:
```swift
struct Foo: ParsableCommand {
@Flag()
var verbose = false
@Flag()
var dryRun = false
mutating func validate() {
if dryRun {
verbose = true    // --dry-run implies --verbose
}
}
func run() {
if verbose { ... }
}
}
```
While this isn't _technically_ a validation step, it's been useful to separate post-processing of the arguments like this from the business logic of `run()`.
I couldn't find anything indicating that #104 intended to change this behavior, so I'm assuming it was a …
=> Store mutations made by validate()

CMakeLists.txt, Sources/ArgumentParserTestHelpers/CMakeLists.txt
- TestHelpers has a implicit dependency on Foundation through
ArgumentParser, so it needs to link against Foundation
- The find package calls should be REQUIRED and CONFIG so they can take
advantage of CMake configs
=> Fix CMake build on Linux

Documentation/01 Getting Started.md
It's not from the get-go clear for beginners that Foundation has to be imported as well. Otherwise, you would end up with a bunch of compilation errors.
- [-] I've added at least one test that validates that my change is working, if appropriate
=> Make it clear that Foundation has to be imported

Sources/ArgumentParser/Completions/CompletionsGenerator.swift, Sources/ArgumentParser/Parsable Properties/Errors.swift, Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift
The Windows environment calls the library `CRT`.  This also enables the
removal of the `visualc` module from the Swift SDK overlay.
=> Windows: migrate to `CRT` from `MSVCRT`

Sources/ArgumentParser/Parsable Types/CommandConfiguration.swift
=> Fix small typo in `CommandConfiguration` documentation

Sources/ArgumentParser/Usage/UsageGenerator.swift
Relates to issue https://forums.swift.org/t/how-to-exclude-members-from-parsing/34325/9
The existing message was completely unhelpful, and even erroneous in the sense that the issue is not related to an argument at all, but to a non-argument. The new message is a stop-gap until the actual problem causing the error is resolved, but it at least gives the user actionable information and makes it clear where the issue lies.
=> Provide more descriptive error message for non-argument variable parsing failure.

Documentation/04 Customizing Help.md, Sources/ArgumentParser/Parsable Types/CommandConfiguration.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Tests/ArgumentParserPackageManagerTests/HelpTests.swift
Modifying help flag names now works for subcommand. If not specified `helpNames` is inherited from parent. This PR is compatible with the current system.
Fix #215
=> Add custom helpNames support for Subcommand

Sources/ArgumentParser/Completions/FishCompletionsGenerator.swift, Sources/ArgumentParser/Parsable Properties/NameSpecification.swift, Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Parsing/InputOrigin.swift, Sources/ArgumentParser/Parsing/Name.swift, Sources/ArgumentParser/Parsing/SplitArguments.swift, Tests/ArgumentParserEndToEndTests/CMakeLists.txt, Tests/ArgumentParserEndToEndTests/JoinedEndToEndTests.swift
This supports joined arguments, like '-Ddebug' or '-v4'. Joined arguments need to be explicitly declared as `.customShort("D", allowingJoined: true)`.
You can now specify a Boolean `allowingJoined` value when declaring a custom short name specification, like this:
```swift
@main
struct Example: ParsableCommand {
@Option(name: .customShort("D", allowingJoined: true))
var debugValue: String
func run() {
print(debugValue)
}
}
```
Existing calls still work as expected:
```
$ example -D debug
debug
$ example -D=debug
debug
```
And now you can use joined syntax:
```
$ example -Ddebug
debug
```
Expanded the documentation for `.customShort(_:allowingJoined:)` on both `NameSpecification` and `NameSpecification.Element`.
Unit tests covering the breadth of usage.
This is an additive change only, …
=> Add support for joined short options

Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsable Properties/Option.swift, Tests/ArgumentParserEndToEndTests/SourceCompatEndToEndTests.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift, Tests/ArgumentParserUnitTests/ParsableArgumentsValidationTests.swift
These were deprecated in version 0.2.0. Time to go!
=> Remove deprecated property wrapper initializers

Documentation/04 Customizing Help.md, Sources/ArgumentParser/Parsable Types/CommandConfiguration.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParser/Usage/MessageInfo.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Tests/ArgumentParserPackageManagerTests/HelpTests.swift
Error messages include a message that shows how to display the help screen, but the message didn't use the custom help flag names for a command if they had been specified.
=> Use the correct help flag in error messages

Sources/ArgumentParser/Completions/FishCompletionsGenerator.swift, Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Sources/ArgumentParser/Parsing/InputOrigin.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Tests/ArgumentParserEndToEndTests/CustomParsingEndToEndTests.swift, Tests/ArgumentParserEndToEndTests/SimpleEndToEndTests.swift
This captures the default value for non-parsable properties when building the ArgumentSet, which in turn get set as initial
values before decoding. Resolves #265.
=> Allow variable properties in parsable types

Sources/ArgumentParser/Usage/MessageInfo.swift, Tests/ArgumentParserUnitTests/ExitCodeTests.swift
Ensures the `NSError` case is handled in `MessageInfo` and attempts to resolve #270
=> Beautify `NSError` cases when thrown 💄 

Sources/ArgumentParser/Usage/UsageGenerator.swift, Tests/ArgumentParserPackageManagerTests/HelpTests.swift, Tests/ArgumentParserUnitTests/UsageGenerationTests.swift
ArgumentParser is configured not to emit detailed synopsis when it would contain more than a dozen entries. This makes sense; however, eliding all information makes the synopsis rather useless.
While commands may have dozens of options, in most cases, only a few of them are required — so we can keep the synopsis short but still useful by only displaying the required parts.
=> Generate useful synopsis for commands with many options

Sources/ArgumentParser/Usage/MessageInfo.swift, Tests/ArgumentParserUnitTests/ExitCodeTests.swift
The error code in CustomNSError is actually _not_ appropriate to use as the command's exit code, as described in #269.
=> Remove special casing for CustomNSError

Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift, Tests/ArgumentParserUnitTests/CompletionScriptTests.swift
=> Fix zsh dashes in command names

Sources/ArgumentParser/Usage/MessageInfo.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Tests/ArgumentParserEndToEndTests/TransformEndToEndTests.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift, Tests/ArgumentParserExampleTests/RepeatExampleTests.swift, Tests/ArgumentParserExampleTests/RollDiceExampleTests.swift
=> Include help text in error message when validation fails

Sources/ArgumentParser/Parsing/ArgumentSet.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
Fixes an issue where the inversion of a flag would not be hidden when the `ArgumentHelp.shouldDisplay` value is `false`.
Added a unit test to check for this behavior.
Example:
```
@Flag(inversion: .prefixedNo, help: .hidden)
var prompt: Bool = true
```
Would produce the following in the help text:
```
OPTIONS:
--no-prompt
```
But the desired outcome is that there is no listing for this flag in the help text.
=> Hide flag inversion when help is hidden

Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Parsing/ArgumentDecoder.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Parsing/InputOrigin.swift, Sources/ArgumentParser/Parsing/ParsedValues.swift, Sources/ArgumentParser/Parsing/ParserError.swift, Sources/ArgumentParser/Utilities/MirrorExtensions.swift, Tests/ArgumentParserEndToEndTests/UnparsedValuesEndToEndTest.swift, Tests/ArgumentParserUnitTests/InputOriginTests.swift, Tests/ArgumentParserUnitTests/MirrorTests.swift
Fixes “Internal error. Invalid state while parsing command-line arguments.” that is encountered when an unparsed value is optional.
Root causes:
- `ParsedArgumentsContainer.decodeNil` returns false for optional values because it only does a `!contains(key)` check. This should instead return nil if the value of the element is nil.
- The decoder did not know about unparsed input origins that and would result in unexpected behavior when decoding nil default values.
- The `value` of `Mirror.Child` is defined as `Any` but this is confusing because the value could be `Optional<Any>` which is not equal to `nil` even when the `Optional` case is `.none`.
=> Fix invalid state error when decoding an unparsed optional value

Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsable Properties/Option.swift, Sources/ArgumentParser/Parsable Properties/OptionGroup.swift, Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
Second PR that is needed to fix --help for SwiftPM
Related PRs:
[SwiftPM](https://github.com/apple/swift-package-manager/pull/3407)
[ArgumentParser](https://github.com/apple/swift-argument-parser/pull/300)
=> Hide option group with new OptionGroup constructor

Sources/ArgumentParser/Completions/BashCompletionsGenerator.swift, Sources/ArgumentParser/Completions/FishCompletionsGenerator.swift, Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift, Tests/ArgumentParserUnitTests/CompletionScriptTests.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
This uses the customized help flags when generating completion scripts and includes the `--version` flag when appropriate. (Fish completions didn't include the help flags at all, which is now fixed as well.)
=> Use custom help flags in completion scripts

Sources/ArgumentParser/Usage/HelpCommand.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift
This resolves #259 — a bit more involved than I expected, as `HelpCommand` uses a custom decoder.
=> Ignore extra help flags when given with the 'help' subcommand

Sources/ArgumentParser/Parsing/ArgumentSet.swift, Tests/ArgumentParserEndToEndTests/JoinedEndToEndTests.swift, Tests/ArgumentParserEndToEndTests/RepeatingEndToEndTests.swift
This fixes a bug where an `@Option` array defined with the `.upToNextOption` parsing strategy would only capture the last "group" of elements. e.g. in:
example --test one two --test three four
the `--test` property would only have the value `["three", "four"]`.
Fixes rdar://73908471
=> Capture values across multiple .upToNextOption option uses

Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsable Properties/Errors.swift, Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsable Properties/NameSpecification.swift, Sources/ArgumentParser/Parsable Properties/Option.swift, Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Usage/MessageInfo.swift
Using structs for these public types (instead of enums) will let us add members in the future without breaking source compatibility. This is a source-breaking change, but not alarmingly so — these enum cases are typically used as static members, and that usage is maintained. Only switch exhaustivity is altered here.
=> Convert all public enums to structs

Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
It appears this issue was fixed some time in the past; closes #278.
=> Add test for issue #278

Sources/ArgumentParser/Completions/BashCompletionsGenerator.swift, Sources/ArgumentParser/Completions/FishCompletionsGenerator.swift, Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift, Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsable Properties/Option.swift, Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Sources/ArgumentParser/Utilities/CollectionExtensions.swift
- Removes one layer of help properties by directly including the members
of ArgumentHelp in ArgumentDefinition.Help. This also results in the
discussion field which previously existed in both structures, now
having a single source of truth. Adds helper method for setting each
of these members using an instance of ArgumentHelp and additionally
annotates each of the String? members with a new `@NonEmpty` property
wrapper that ensures the wrapped string is either nil or nonempty so
clients no do not need to check for the empty string case.
=> Clean up internal property nesting

Sources/ArgumentParser/Completions/BashCompletionsGenerator.swift, Sources/ArgumentParser/Completions/CompletionsGenerator.swift, Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Parsing/Name.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift
- Removes unused codepaths.
- Simplifies synopsis string codepaths by removing optionality. This
complexity is moved to the caller who is now responsible for filtering
out hidden arguments and options. This change is desirable as it
allows the caller to determine if the argument should be hidden. For
example, while it makes sense to hide arguments in help text, it may
not make sense to hide them when dumping the arguments for another
tool to consume.
=> Simplify synopsis string generation

Sources/ArgumentParser/CMakeLists.txt
apple/swift-argument-parser#315 added a new file but failed to update
the CMakeLists.txt, resulting in the inability to bootstrap the
toolchain.
=> build: update the build rules for ArgumentParser

Sources/ArgumentParser/Completions/BashCompletionsGenerator.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift
I’ve noticed when using a custom completion in bash, the custom completion handler does not receive all the arguments as would be expected. This PR fixes that.
=> Fix custom completion args for bash

Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
At first I noticed a crash when running the tests of this project. It was due to weird chars in my CWD.
This lead me to discover a bug where the default value description of a URL checks for the `absoluteString` value of itself instead of the path + whether it is a file URL!
Note: I did not add a test specifically, I don’t really know how this would be tested. Maybe create a folder with a weird name and check everything is good? Also a test with an https URL as default w/ a path being the same as current CWD?
Tell me, I’ll do them if needed.
=> Fix default value description for URL

Sources/ArgumentParser/Usage/UsageGenerator.swift, Tests/ArgumentParserExampleTests/RepeatExampleTests.swift, Tests/ArgumentParserExampleTests/RollDiceExampleTests.swift, Tests/ArgumentParserPackageManagerTests/HelpTests.swift
Hi, these changes should fix #314.
=> Included help message when a required value is missing.

Sources/ArgumentParser/Completions/BashCompletionsGenerator.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift
In Bash, when calling completion for an executable written with full path (e.g. `/opt/brew/bin/example`), the completion script might call another executable if another executable with the same name happens to be first in the PATH. (This is particularly annoying when debugging completion in a project!) This PR fixes that.
=> Fix executable path when calling custom completion in bash

Documentation/06 Manual Parsing and Testing.md
Fixed minor syntax error in Documentation/06 Manual Parsing and Testing.md
=> [documentation] Fix guard syntax error in 06 Manual Parsing and Testing

Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Tests/ArgumentParserEndToEndTests/RepeatingEndToEndTests.swift
If a command defines an `@Argument` property with the `.unconditionalRemaining` parsing strategy, we need to stop parsing input when we encounter either a positional argument or an unrecognized option/flag label. Note that this is a change in behavior, as seen in the modified test.
Resolves #331.
=> Stop parsing earlier when a catch-all argument is present

Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
- Adds an overload of ArgumentDefinition.init with a generic constraint
on ExpressibleByArgument that propogates the conformance to the
construction of ArgumentDefinition.Help. This allows the
allValueStrings of the type conforming to ExpressibleByArgument to
become the allValues property of the help object.
Fixes #340
=> Propogate ExpressibleByArgument conformance

Examples/repeat/main.swift, Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsable Properties/Option.swift, Sources/ArgumentParser/Parsable Properties/OptionGroup.swift, Sources/ArgumentParser/Parsable Types/ParsableArguments.swift
ArgumentParser version 0.4.3 added an experimental feature for hiding option groups at the command level, which is triggering a runtime crash when commands are compiled in release mode, as described in #338 and rdar://80796582. This includes changes that work around both of those crashes. I'll cherry pick this change over to the current release as 0.4.4 as well.
=> Work around runtime issue introduced in 0.4.3

Sources/ArgumentParser/CMakeLists.txt, Sources/ArgumentParserToolInfo/CMakeLists.txt, Sources/CMakeLists.txt
The changes in #335 introduced a new library but failed to actually
build the library and update the dependency structure.  Update the build
system to build and install the new target.
=> build: repair the build of ArgumentParser with CMake

Sources/ArgumentParser/Parsable Properties/Errors.swift, Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParserTestHelpers/TestHelpers.swift, Tests/ArgumentParserUnitTests/DumpHelpGenerationTests.swift
This marks the two entry points of the "dump help" feature as experimental.
1. The `--dump-help` flag is now `--experimental-dump-flag`
2. The `dumpMessage()` method on `ParsableArguments` has been renamed to `_dumpHelp()`
This feature isn't covered in the documentation yet.
Updated the test with new names, as above.
None — this feature hasn't yet shipped in a release.
=> Mark the dump help feature as experimental for now

Sources/ArgumentParser/Usage/DumpHelpGenerator.swift
This PR fixes compile failure on iOS, which happens if you are adding CLI support for a Mac Catalyst app. Specifically, it fixes:
```
'sortedKeys' is only available in iOS 11.0 or newer
```
- [N/A] I've added at least one test that validates that my change is working, if appropriate
- [N/A] I've updated the documentation if necessary
=> Fix compile failure on iOS for Mac Catalyst support

Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift, Tests/ArgumentParserUnitTests/CompletionScriptTests.swift
- #277 
- #284 
This adds onto the fix from #284 that added support for commands with dashes in the name. 
When getting completions for an argument using `CompletionKind.custom(...)` an error occurs. #284 updated [a variable](https://github.com/apple/swift-argument-parser/pull/284/files#diff-b243e9c8a946a341ab514c2d5ce1b9f27a3bb6cf672b14ab02f0d221a491d645R20) but missed updating where that variable is used to also escape the command name.
This updates the usage of that variable to also escape the command name and updates the tests to check for it.
If I have a command called `cli-tools` with an argument that has a `CompletionKind.custom(...)`, typing `cli-tools a` then pressing tab will produce the following error.
```
cli-tools a_custom_completion:1: command not found: -tools_commandname …
```
=> Fixed custom completion not working in zsh when command name contains a dash

Sources/ArgumentParser/Completions/FishCompletionsGenerator.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift, Tests/ArgumentParserUnitTests/CompletionScriptTests.swift
This PR has two minor changes for FishCompletionsGenerator.swift.
The first is related to the name of the fish function created that's used to determine whether to show completions or not, depending on the commandline entered thus far. Functions beginning with `__fish` **really** ought only be things internal to fish that are included with the shell. So prefix the function `_swift` instead.
Secondly, `set --local cmd` instead of `set cmd` - this ensures running the function does not accidentally clobber a global or universal variable.
=> Rename `...using_command` fish function, set `$cmd` in local scope

Sources/ArgumentParser/Usage/UsageGenerator.swift, Tests/ArgumentParserUnitTests/ErrorMessageTests.swift
When an option value fails to parse, no custom error message is
provided, and a list of valid candidate values is available, include the
list as part of the error message.
Addresses #344.
=> List valid options in error messages

Sources/ArgumentParser/Usage/HelpGenerator.swift
- Fixes #369
- Adds an error check for the return value of GetConsoleScreenBufferInfo
Windows. If GetConsoleScreenBufferInfo a default size of 80 by 25 is
used.
=> Handle failures getting terminal size on windows

Sources/ArgumentParser/Usage/DumpHelpGenerator.swift
- Fixes #375
- Fixes a bug with the experimental dump help generator which would
occur when a ParsableCommand has non-Argument properties.
=> Fix dump help crash

Sources/ArgumentParser/Usage/HelpCommand.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParser/Utilities/StringExtensions.swift, Tests/ArgumentParserPackageManagerTests/HelpTests.swift
- Adds check to ensure that `wrapped(to:wrappingIndent:)` doesn't
attempt to retrieve a negative prefix.
- The Usage struct was composed of an array of strings which always
contained exact one string at runtime. This struct has been removed
and replaced with a single usage string.
- Removes HelpGenerator._screenWidthOverride in favor of explicitly
setting the screen width in generateHelp calls.
=> Clean up help generation

Sources/ArgumentParser/Completions/FishCompletionsGenerator.swift, Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsable Properties/Option.swift, Sources/ArgumentParser/Parsing/InputOrigin.swift, Sources/ArgumentParser/Parsing/SplitArguments.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Sources/ArgumentParser/Utilities/SequenceExtensions.swift, Tests/ArgumentParserEndToEndTests/ValidationEndToEndTests.swift
Corrects a number of typos that I saw throughout comments in the codebase.
| Original | Replacement |
|----|----|
| avaiable | available |
| favour | favor |
| occurence | occurrence |
| Onl | |
| propery | property |
| sinlge | single |
| suggetion | suggestion |
| tranform | transform |
- [N/A] I've added at least one test that validates that my change is working, if appropriate
- [N/A] I've followed the code style of the rest of the project
- [N/A] I've updated the documentation if necessary
=> Correct Typos

Sources/ArgumentParser/Documentation.docc/Articles/CustomizingHelp.md, Sources/ArgumentParser/Parsable Properties/ArgumentHelp.swift, Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
This pull request (as a draft for now) adds a new `ArgumentHelp.Visibility` API with multiple levels allowing to indicate whether help messages should be shown in the extended help display.
It follows suggestions made by @natecook1000 in issue https://github.com/apple/swift-argument-parser/issues/384.
=> ArgumentHelp.Visibility levels API

Sources/ArgumentParser/Parsable Properties/Option.swift, Tests/ArgumentParserEndToEndTests/DefaultsEndToEndTests.swift
This PR marks an `Option` initializer as deprecated because it had its last 2 parameters inverted (help should be before completion, following order of all other initializers).
It also adds a new one with parameters in correct order.
It follows recommendations of @natecook1000 in issue https://github.com/apple/swift-argument-parser/issues/381.
=> Deprecate Option initializer and add a new one with parameters in order

Sources/ArgumentParser/Parsable Properties/Option.swift
This pull request harmonizes `Option` initializers abstracts by providing documentation to `completionKind` arguments.
=> Harmonize Option initializers abstracts

Sources/ArgumentParser/Parsable Types/ParsableCommand.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Tests/ArgumentParserEndToEndTests/DefaultSubcommandEndToEndTests.swift
This extends the current behavior of `@Argument` array properties defined with the `.unconditionalRemaining` parsing strategy to work with subcommands, as well. For example, with a command hierarchy like this:
```swift
@main
struct Root: ParsableCommand {
static var configuration: CommandConfiguration {
.init(subcommands: [Sub.self])
}
@Flag var verbose = false
}
struct Sub: ParsableCommand {
@Argument(parsing: .unconditionalRemaining)
var remainder: [String] = []
@OptionGroup var root: Root
func run() {
print("Verbose:", root.verbose)
print("Remainder:", remainder)
}
}
```
We want the `Sub` command to capture any arguments after the subcommand name appears in the command-line arguments. This fix enables the following behavior:
```
$ root --verbose sub foo --bar
Verbose: true
Remainder: …
```
=> Fix issue with unconditional remaining properties in subcommands

Sources/ArgumentParser/CMakeLists.txt, Sources/ArgumentParser/Completions/BashCompletionsGenerator.swift, Sources/ArgumentParser/Completions/FishCompletionsGenerator.swift, Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift, Sources/ArgumentParser/Parsable Properties/ArgumentHelp.swift, Sources/ArgumentParser/Parsable Properties/ArgumentVisibility.swift, Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Sources/ArgumentParser/Usage/DumpHelpGenerator.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift
- Renames ArgumentHelp.Visibility to ArgumentVisibility.
- Replaces ArgumentDefinition.shouldDisplay with a visibility property
whose value is derived from ArgumentHelp.visibility.
=> Forward ArgumentVisibility to ArgumentDefinition

Sources/ArgumentParser/CMakeLists.txt, Sources/ArgumentParser/Completions/BashCompletionsGenerator.swift, Sources/ArgumentParser/Completions/FishCompletionsGenerator.swift, Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift, Sources/ArgumentParser/Parsable Properties/ArgumentHelp.swift, Sources/ArgumentParser/Parsable Properties/ArgumentVisibility.swift, Sources/ArgumentParser/Parsable Properties/OptionGroup.swift, Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Sources/ArgumentParser/Usage/DumpHelpGenerator.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
- Deprecates OptionGroup.init(_hiddenFromHelp:) and replaces it with
OptionGroup.init(_visibility:).
- Updates ArgumentSetProvider to use _visibility.
=> Update OptionGroup to use Visibility

Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParserTestHelpers/TestHelpers.swift, Tests/ArgumentParserPackageManagerTests/HelpTests.swift
- Adds help-hidden flags generated based on each ParsableCommand's help
names. The help-hidden flag is only generated if the help names
contain at least one .long name.
=> Provide non-experimental help-hidden flags

Sources/ArgumentParser/Documentation.docc/Extensions/ParsableArguments.md, Sources/ArgumentParser/Documentation.docc/Extensions/ParsableCommand.md, Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Parsable Types/ParsableCommand.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParserTestHelpers/TestHelpers.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
- Updates helpMessage(columns:) and helpMessage(for:columns:) with an
includeHidden argument defaulted to false to allow for clients to
programmatically generate hidden help.
=> Add abillity to generate hidden help

Sources/ArgumentParser/Completions/BashCompletionsGenerator.swift, Sources/ArgumentParser/Completions/FishCompletionsGenerator.swift, Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift, Sources/ArgumentParser/Parsable Properties/ArgumentVisibility.swift, Sources/ArgumentParser/Parsable Properties/OptionGroup.swift, Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Parsable Types/ParsableCommand.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Usage/DumpHelpGenerator.swift, Sources/ArgumentParser/Usage/HelpCommand.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParser/Usage/MessageInfo.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
- Replaces `ArgumentSet.init(_:creatingHelp:includeHidden:)` with
`ArgumentSet.init(_:visibility:)`. `visibility` intentionally does not
have a default value to ensure that callers only have the correct
arguments. As part of this change `includeHidden` has been replaced
throughout the codebase with `visibility`. This change also fixes a
bug where arguments with hidden `visibility` were being displayed in the
generated command usage string.
=> Replace createHelp and includeHidden

Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift, Tests/ArgumentParserUnitTests/UsageGenerationTests.swift
This includes arguments, options, and flags that have `.hidden` visibility when a user requests the extended version of help with `--help-hidden`. Previously, only hidden option groups were included.
=> Show hidden args/opts/flags with --help-hidden

Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Tests/ArgumentParserUnitTests/UsageGenerationTests.swift
The usage string feature that only shows positional args and required options/flags was incorrectly allowing through flags with type `Bool?`. For example, `--enable-foo` was incorrectly visible in the usage string for this type:
```swift
struct Example: ParsableCommand {
// so many options
// too many options
@Flag(inversion: .prefixedEnableDisable)
var foo: Bool?
}
```
=> Hide optional flags when a command has too many options

Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Parsing/SplitArguments.swift, Tests/ArgumentParserEndToEndTests/DefaultSubcommandEndToEndTests.swift
Previously, a `--help` flag could trigger the help screen when it should have been part of the parsed input for a command with an `.unconditionalRemaining` array parsing strategy.
=> Don't trigger help for commands w/ unconditional remaining

.github/PULL_REQUEST_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE/NEW.md, Sources/ArgumentParser/Parsable Properties/Errors.swift
I found a typo and realized some links were not working in the PR template.
No real code was harmed during the production of this PR. 😅 
- ~~I've added at least one test that validates that my change is working, if appropriate~~
- ~~I've followed the code style of the rest of the project~~
=> Fix a typo and template links

Sources/ArgumentParser/Parsable Properties/OptionGroup.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
This removes the underscore from the parameter in `@OptionGroup(visibility:)`, making it a fully public API. This allows users to set the visibility for an entire option group at once.
This adds a single initializer to the `OptionGroup` type.
```swift
extension OptionGroup {
init(visibility: ArgumentVisibility)
}
```
Symbol documentation included.
Updated tests for generating help.
This deprecates, but doesn't remove, the no argument `OptionGroup` initializer.
=> Make `@OptionGroup(visibility:)` a public API

Examples/CMakeLists.txt
This fixes the build with CMake after #404.
=> build: repair the build after #404

Examples/count-lines/CountLines.swift, Package.swift, Sources/ArgumentParser/Parsable Types/AsyncParsableCommand.swift
Adding the platform requirement is a source breaking change; this moves the requirement down to the `async` symbols instead.
Fixes #426.
=> Remove platform requirement from Package.swift

Examples/CMakeLists.txt
This adds `-parse-as-library` to the example targets which use `@main`
resulting in a compile failure as `@main` is not processed unless the
target is marked as library.
=> build: complete the changes from #423

Sources/ArgumentParserToolInfo/CMakeLists.txt
Now that windows supports static linking as well (to a certain degree),
alter the build of swift-argument-parser in CMake to use static linking
for ArgumentParserToolInfo always irrespective of whether ArgumentParser
is being built as a static library or a dynamic library.  On Windows, in
release mode, this saves ~32KiB.  Additionally, because no tool directly
links against this library, no binaries are further expanded by static
linking, and we have one less file to distribute.
=> build: statically link ArgumentParserToolInfo always

Examples/repeat/Repeat.swift, README.md, Sources/ArgumentParser/Documentation.docc/ArgumentParser.md, Sources/ArgumentParser/Documentation.docc/Articles/CustomizingCommandHelp.md, Sources/ArgumentParser/Documentation.docc/Extensions/ParsableCommand.md, Tests/ArgumentParserExampleTests/RepeatExampleTests.swift
To prevent newbies from being scared off by endless printing in the terminal, I changed the default value of `Repeat.count` from `.max` to `2`.
=> Fix Repeat's endless printing

Sources/ArgumentParser/Parsable Properties/Option.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Tests/ArgumentParserUnitTests/ErrorMessageTests.swift
Here's my solution to issue #434. I've written some unit tests and passed all tests, but I still don't know if there are any omissions or is there a way to be more performant. Every thoughts are welcomed.
=> Fix error message for `@Option`

Sources/ArgumentParser/Completions/BashCompletionsGenerator.swift, Sources/ArgumentParser/Completions/FishCompletionsGenerator.swift, Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift, Tests/ArgumentParserUnitTests/CompletionScriptTests.swift
- Adds a filter to prevent hidden subcommands from appearing in shell
completion scripts.
Fixes #442, rdar://92182881
=> Hide hidden subcommands from completions

Sources/ArgumentParser/Parsable Properties/Argument.swift, Tests/ArgumentParserUnitTests/ErrorMessageTests.swift
When an array of argument values fails to parse, no custom error message is
provided, and a list of valid candidate values is available, include the
list as part of the error message.
Addresses #401.
=> List valid options in error messages for enum array argument

Sources/ArgumentParser/Utilities/StringExtensions.swift, Tests/ArgumentParserUnitTests/StringEditDistanceTests.swift
Improving implementation of edit distance string extension by:
* Using only two arrays `n + 1` instead of an `m x n` matrix.
* Trimming common prefix and suffix as an optimization for reducing size/complexity 
* Tests for those cases were added.
Been playing around with ways to improve it more in https://github.com/LucianoPAlmeida/strings
**Benchmarks**
**Code:**
```swift
var benchmark = Benchmark(title: "Edit distance")
let inputGeneratorCommon: (Int) -> (String, String) = { size in
let common = String(repeating: "a", count: size / 4)
let s1 = String(repeating: "foo", count: (size / 2) / 3)
let s2 = String(repeating: "bar", count: (size / 2) / 3)
return (common + s1 + common, common + s2 + common)
}
let inputGeneratorDifferent: (Int) -> (String, String) = { size in
let s1 = …
```
=> [NFC] Improving edit distance string extension

Package@swift-5.6.swift
✅ Closes: #455
`ArgumentParser` 1.1.3 includes a SwiftPM plugin for generating man pages. However, this plugin is not visible to packages that declare `ArgumentParser` as a package dependency.
Defining a product of type `plugin` in the package manifest will solve that. Running `swift package plugin --list` for a package, that declares `ArgumentParser` as a package dependency, will then list the `GenerateManualPlugin`
```
‘experimental-generate-manual’ (plugin ‘GenerateManualPlugin’ in package ‘swift-argument-parser’)
```
=> fix: 🐛 Declare `GenerateManualPlugin` as plugin product

Plugins/GenerateManualPlugin/GenerateManualPlugin.swift, Plugins/GenerateManualPlugin/GenerateManualPluginError.swift, Tests/ArgumentParserGenerateManualTests/CountLinesGenerateManualTests.swift, Tests/ArgumentParserGenerateManualTests/MathGenerateManualTests.swift, Tests/ArgumentParserGenerateManualTests/RepeatGenerateManualTests.swift, Tests/ArgumentParserGenerateManualTests/RollDiceGenerateManualTests.swift, Tools/generate-manual/DSL/Authors.swift, Tools/generate-manual/DSL/Core/ForEach.swift, Tools/generate-manual/DSL/SeeAlso.swift
- Fixes an issue where the --author option without its value  was passed
by the generate-manual plugin to the generate-manual tool resulting in
plugin invocation failures or incorrect author information.
=> Fix generate-manual plugin authors argument

Tests/ArgumentParserGenerateManualTests/CountLinesGenerateManualTests.swift, Tests/ArgumentParserGenerateManualTests/MathGenerateManualTests.swift, Tests/ArgumentParserGenerateManualTests/RepeatGenerateManualTests.swift, Tests/ArgumentParserGenerateManualTests/RollDiceGenerateManualTests.swift, Tools/generate-manual/DSL/ArgumentSynopsis.swift
- Fixes a manual generation bug where options in the synopsis were not
given an option value name and flags were.
=> Fix missing option value names in manuals

Sources/ArgumentParser/Parsable Properties/ArgumentVisibility.swift, Sources/ArgumentParserTestHelpers/TestHelpers.swift
In addition to being useful, this allows us to drop the `@testable` annotation for the ArgumentParser import in ArgumentParserTestHelpers, which resolves #463.
=> Declare Hashable conformance for ArgumentVisibility

Sources/ArgumentParser/Parsable Types/ParsableArgumentsValidation.swift, Tests/ArgumentParserUnitTests/ParsableArgumentsValidationTests.swift
If a ParsableArguments type doesn't implement init(from:) correctly, it isn't decodable by the parser. This improves the validation failure message for such types.
=> Add a validation message for an invalid decoder

Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsable Properties/Option.swift, Sources/ArgumentParser/Parsable Types/ExpressibleByArgument.swift, Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Parsing/ParserError.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParserTestHelpers/TestHelpers.swift, Tests/ArgumentParserExampleTests/CountLinesExampleTests.swift, Tests/ArgumentParserGenerateManualTests/CountLinesGenerateManualTests.swift, Tests/ArgumentParserUnitTests/CMakeLists.txt, Tests/ArgumentParserUnitTests/HelpGenerationTests+AtArgument.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests+AtOption.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
- Fixes #466.
- Adds initializers to ArgumentDefinition generic over a Container type.
The Container type must conform to a new internal protocol
ArgumentDefinitionContainer which describes functionality like default
set of help options for the argument defined by the property wrapper,
etc.
- Adds overloads for Optional @Arguments and @Options with default
values which emit deprecation warning to guide users towards using the
non-Optional versions.
=> Unify @Argument and @Option initialization paths

Examples/count-lines/CountLines.swift, Examples/math/Math.swift, Examples/repeat/Repeat.swift, Examples/roll/main.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Parsing/Interactive.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
=> [GSoC] Interactive mode should only run in an interactive shell

Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Tests/ArgumentParserEndToEndTests/FlagsEndToEndTests.swift, Tests/ArgumentParserPackageManagerTests/HelpTests.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
When an `EnumerableFlag` flag has a default value, the default is printed incorrectly as the instance value in the help, instead of as the flag that a user would need to type. The same issue is present for Boolean flags with both an inversion and a default.
```swift
struct Example: ParsableCommand {
@Flag(inversion: .prefixedNo)
var frobulate: Bool = true
}
```
Old help output:
```
USAGE: example [--frobulate] [--no-frobulate]
OPTIONS:
--frobulate/--no-frobulate
Whether to frobulate. (default: true)
-h, --help              Show help information.
```
Corrected help output:
```
USAGE: example [--frobulate] [--no-frobulate]
OPTIONS:
--frobulate/--no-frobulate
Whether to frobulate. (default: --frobulate)
-h, --help              Show help information.
```
=> Fix default display in help for `EnumerableFlag` and other types

Sources/ArgumentParser/Parsable Properties/Flag.swift
This restores the ability to build with versions of Swift prior to 5.7.
=> Add an explicit return type to `flatMap` closure.

Sources/ArgumentParser/Parsable Types/ExpressibleByArgument.swift, Tests/ArgumentParserUnitTests/ErrorMessageTests.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
RawRepresentable types that have a non-String raw value are having values displayed in the help screen by converting the RawRep value into a string. However, these values are by default parsed by their raw value, so we should use that for display instead.
This is accomplished by adding a defaultValueDescription implementation for all ExpressibleByArgument-conforming RawValue types, and then basing the allValues implementation on that. This generalizes the existing overloads for String-based RawRep types, while also allowing users who customize their ExpressibleByArgument implementation to provide the correct help value for clients.
=> Fix help display for non-String RawRepresentables

Sources/ArgumentParser/Completions/BashCompletionsGenerator.swift, Sources/ArgumentParser/Completions/CompletionsGenerator.swift, Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsable Properties/NameSpecification.swift, Sources/ArgumentParser/Parsable Properties/OptionGroup.swift, Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Parsable Types/ParsableArgumentsValidation.swift, Sources/ArgumentParser/Parsable Types/ParsableCommand.swift, Sources/ArgumentParser/Parsing/ArgumentDecoder.swift, Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Parsing/InputKey.swift, Sources/ArgumentParser/Parsing/ParsedValues.swift, Sources/ArgumentParser/Usage/DumpHelpGenerator.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParser/Usage/MessageInfo.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Tests/ArgumentParserEndToEndTests/DefaultsEndToEndTests.swift, Tests/ArgumentParserEndToEndTests/OptionGroupEndToEndTests.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift, Tests/ArgumentParserUnitTests/NameSpecificationTests.swift, Tests/ArgumentParserUnitTests/ParsableArgumentsValidationTests.swift, Tests/ArgumentParserUnitTests/UsageGenerationTests.swift
This fix addresses the core issue described in #322.
As noted in the issue, if you have a `ParsedCommand`/`AsyncParsedCommand` which contains a `ParsedArguments` implementation, and the `ParsedCommand` and `ParsedArguments` both have a field which has the same name and type, they will both update each other, even if one has a unique `.customLong(...)` name.
For example, a simple case which will break:
```swift
struct MyOptions: ParsedArguments {
@Flag(name: .customLong("my-custom-flag"))
var myFlag: Bool = false
}
struct MyCommand: ParsedCommand {
@Flag()
var myFlag: Bool = false
@OptionGroup var options: MyOptions
mutating func run() throws {
print("My Flag: \(myFlag)")
print("My Custom Flag: \(options.myFlag)")
}
}
```
This is then output with flags set:
```sh
> swift run MyCommand
My …
```
=> Fixes incorrect value copying when ParseArguments has the same field name+type as the ParseCommand  (Issue #322)

Sources/ArgumentParser/Documentation.docc/Articles/CustomizingHelp.md, Sources/ArgumentParser/Parsable Properties/OptionGroup.swift, Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Sources/ArgumentParser/Usage/DumpHelpGenerator.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParser/Utilities/CollectionExtensions.swift, Sources/ArgumentParser/Utilities/StringExtensions.swift, Sources/ArgumentParserToolInfo/ToolInfo.swift, Tests/ArgumentParserUnitTests/CMakeLists.txt, Tests/ArgumentParserUnitTests/DumpHelpGenerationTests.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests+GroupName.swift
This change lets you provide a title for option groups, which is used when generating the help screen. Titled option groups, when they exist, are placed between the ARGUMENTS and OPTIONS section of the help. Multiple option groups with the same title are coalesced into a single group.
For example, this command declaration:
```swift
struct Extras: ParsableArguments {
@Flag(help: "Print extra output while processing.")
var verbose: Bool = false
@Flag(help: "Include details no one asked for.")
var oversharing: Bool = false
}
@main
struct Example: ParsableCommand {
@OptionGroup(title: "Extras")
var extras: Extras
@Argument var name: String?
@Option var title: String?
}
```
yields this help screen:
USAGE: example [--verbose] [--oversharing] [<name>] [--title <title>]
ARGUMENTS:
<name>
EXTRAS: …
=> Add API for titling an option group

Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Parsing/SplitArguments.swift, Tests/ArgumentParserEndToEndTests/CMakeLists.txt, Tests/ArgumentParserEndToEndTests/DefaultSubcommandEndToEndTests.swift, Tests/ArgumentParserEndToEndTests/RepeatingEndToEndTests+ParsingStrategy.swift, Tests/ArgumentParserEndToEndTests/RepeatingEndToEndTests.swift
This adds two new parsing options for argument arrays, and renames `.unconditionalRemaining` to `.captureForPassthrough`:
- `unconditionalRemaining` has been an attractive nuisance. It looks like it means "everything leftover", but it actually has a specific and slightly strange set of behaviors to support SwiftPM capturing inputs to pass on to a sub-client, as in `swift run MyExecutableTarget`. The new name better matches this intended usage.
- `allUnrecognized` collects all the inputs that weren't used during parsing, which is a more generally useful behavior. This essentially suppresses all "unrecognized flag/option" and "unexpected argument" errors, and makes those extra inputs available to the client.
- `postTerminator` collects all inputs that follow the `--` terminator, before …
=> Add two new `ArgumentArrayParsingStrategy` options

Sources/ArgumentParser/CMakeLists.txt
The new source file was added to the tree but not the build.  Due to the snapshots using a tagged version, this escaped testing.
=> build: repair the ArgumentParser build on main

Sources/ArgumentParser/Utilities/Platform.swift
There are references to functions from the Windows SDK rather than the C library for the console handling.  Explicitly import the necessary types and functions from the WinSDK module so that Windows can build once more with the changes to sequester the platform specific code.
=> ArgumentParser: repair the build after #504

Sources/ArgumentParser/Documentation.docc/Extensions/Argument.md, Sources/ArgumentParser/Documentation.docc/Extensions/ArgumentArrayParsingStrategy.md, Sources/ArgumentParser/Documentation.docc/Extensions/Flag.md, Sources/ArgumentParser/Documentation.docc/Extensions/Option.md, Sources/ArgumentParser/Documentation.docc/Extensions/OptionGroup.md, Sources/ArgumentParser/Documentation.docc/Extensions/ParsableArguments.md, Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsable Types/ParsableCommand.swift
Some of the symbol identifiers changed since the last release, and `OptionGroup` and `ArgumentArrayParsingStrategy` both received new API.
=> Update DocC curation for newest symbols

Package@swift-5.6.swift
This PR updates the name of the "Generate Manual" plugin so that it appears in a more readable "command" form in the context menu in Xcode.
Before:
After:
=> Change name of plugin target to readable form

Sources/ArgumentParser/Documentation.docc/Extensions/Argument.md, Sources/ArgumentParser/Documentation.docc/Extensions/Option.md
This fixes 6 unresolved symbol links in ArgumentParser documentation and removes the `@Comment` directives that used to describe these unresolved links. These unresolved links were brought up in https://github.com/apple/swift-docc/issues/407.
This is a documentation-only change.
=> Fix unresolved symbol links in documentation

Sources/ArgumentParser/Documentation.docc/Articles/CommandsAndSubcommands.md, Sources/ArgumentParser/Documentation.docc/Articles/GettingStarted.md, Sources/ArgumentParser/Documentation.docc/Extensions/AsyncParsableCommand.md, Sources/ArgumentParser/Documentation.docc/Extensions/ParsableCommand.md
This will hopefully provide better for guidance around a common issue for ArgumentParser adopters. Also fixes #508.
=> Document changing file name when adding @main

.gitignore, Package.swift, Sources/ArgumentParser/Parsing/InputKey.swift, Tests/ArgumentParserExampleTests/CountLinesExampleTests.swift
We've had some regressions under Swift 5.6 in the latest changes, particularly around using implicitly opened existentials, which is a 5.7 feature. I've tested these changes using Swift 5.6 on Linux and macOS 12.
=> Fix some Swift 5.6 compatibility issues

.spi.yml
This adds the `.spi.yml` file that SPI uses to know how to generate documentation, as described here: https://blog.swiftpackageindex.com/posts/auto-generating-auto-hosting-and-auto-updating-docc-documentation/
=> Add .spi.yml for Swift Package Index doc support

Sources/ArgumentParser/Utilities/Platform.swift
This issue was introduced by #504.
When the target platform is WASI, `Platform.exit` causes infinite recursion because it calls itself.
=> WASI: Fix Platform.exit's infinite recursion

Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsable Properties/Option.swift, Tests/ArgumentParserEndToEndTests/DefaultsEndToEndTests.swift
This change is to make sure that the non-optional generic parameter type is chosen for `@Argument` and `@Option` properties that provide a default value. Previously, an optional type might be chosen depending on how the `help` parameter was spelled, due to strange overload resolution. In particular, using the `.init` caused selection of the deprecated optional overload:
```swift
// Unexpected:
// Infers `Value` as `Optional<AbsolutePath>`
@Argument(help: .init("The path"))
var path = AbsolutePath("/")
// Expected:
// Infers `Value` as `AbsolutePath`
@Argument(help: "The path")
var path = AbsolutePath("/")
```
This addresses the issue by marking the deprecated overloads as disfavored. rdar://102383455
=> Disfavor deprecated property wrapper inits

Tests/ArgumentParserUnitTests/HelpGenerationTests+AtArgument.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests+AtOption.swift
- Fixes deprecation warnings in unit tests by marking tests which cover deprecated functionality as @available(*, deprecated) themselves.
=> Fix deprecation warnings in unit tests

Plugins/GenerateManualPlugin/GenerateManualPlugin.swift, Sources/ArgumentParser/Usage/DumpHelpGenerator.swift, Sources/ArgumentParser/Usage/MessageInfo.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift
- Changes uses of import Foundation in ArgumentParser to only expose the symbols needed to avoid growing unintentional dependencies.
- Replaces direct usage of EXIT_FAILURE in MessageInfo with ExitCode, exposed as a result of the above change.
=> Cleanup Foundation usage

Sources/ArgumentParserTestHelpers/TestHelpers.swift, Tests/ArgumentParserEndToEndTests/SubcommandEndToEndTests.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
- Renames AssertEqualStringsIgnoringTrailingWhitespace to AssertEqualStrings and updates the implementation to require matching trailing whitespace.
- Updates AssertEqualStrings to include much easier to read diff output when CollectionDifference is available. This should add developers when tests fail by providing more clear errors.
=> Update tests with easier to read diff output

index.html
This is part of the concerted effort to move to Swift Package Index hosted docs.
=> Redirect to Swift Package Index hosted docs

index.html
Reverts apple/swift-argument-parser#531 — I mis-read which branch this was landing on. We need to wait until there's a release version of the docs hosted at SPI.
=> Revert "Redirect to Swift Package Index hosted docs"

Sources/ArgumentParser/Completions/FishCompletionsGenerator.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift, Tests/ArgumentParserUnitTests/CompletionScriptTests.swift
A generated fish script didn't complete an option after an argument.
The cause is the generated fish script doesn't accept an input text which already has arguments. 
For example, when the input is `repeat -`, the script can complete `--count`, but when the text is `repeat foo -`, the script cannot complete `repeat foo --count`, because the input text already has the argument "foo".
To fix the issue, I implemented the following steps.
1. Preprocess for the subcommand.
To support options of the root command like `math --version add`, `--version` is removed by `_swift_{command name}_preprocessor`.
2. Decide a command.
In a case when a command has some subcommands like `math stats average 1 10 100 --kind mean`, we need to decide the target command.  (In the example  case, the target command …
=> Improve fish completion (#376, #534)

CHANGELOG.md, README.md
Together with https://github.com/apple/swift-argument-parser/pull/531, updating GitHub pages references to those hosted by Swift Package Index.
=> Change doc references

Sources/ArgumentParser/Usage/UsageGenerator.swift, Tests/ArgumentParserUnitTests/UsageGenerationTests.swift
The purpose of this PR is to fix issue https://github.com/apple/swift-argument-parser/issues/541. It fixes the `USAGE` text when generated with arguments using the `.postTerminator` parsing strategy.
=> Fix .postTerminator usage message

Sources/ArgumentParser/Completions/FishCompletionsGenerator.swift
This provide type annotation for a multi-line closure, which can only have an inferred return type in Swift 5.7.
=> Fix Swift 5.6 compatibility

Sources/ArgumentParser/Parsable Types/ParsableCommand.swift
When an executable with asynchronous commands is backdeployed, the compiler chooses the synchronous `main()` unless a minimum availability target is provided for the root command type. This changes the error message provided when the incorrect `main()` function is called to direct the tool's author to a correct solution.
=> Improve failure message for backdeployed AsyncParsableCommand

Sources/ArgumentParser/Completions/BashCompletionsGenerator.swift, Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsable Properties/NameSpecification.swift, Sources/ArgumentParser/Parsable Properties/OptionGroup.swift, Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Parsable Types/ParsableArgumentsValidation.swift, Sources/ArgumentParser/Parsable Types/ParsableCommand.swift, Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Parsing/InputKey.swift, Sources/ArgumentParser/Usage/DumpHelpGenerator.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParser/Usage/MessageInfo.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Tests/ArgumentParserEndToEndTests/DefaultsEndToEndTests.swift, Tests/ArgumentParserEndToEndTests/OptionGroupEndToEndTests.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift, Tests/ArgumentParserUnitTests/NameSpecificationTests.swift, Tests/ArgumentParserUnitTests/ParsableArgumentsValidationTests.swift, Tests/ArgumentParserUnitTests/UsageGenerationTests.swift
When a property wrapper is applied to a property, the property's storage is given a name with a prefixed underscore. That is, for a property named `x`, the actual storage is named `_x`.
That prefixed storage is what is visible through reflection, so when building an `ArgumentSet` from a command type's mirror, we need to remove the leading underscore. This is done when creating an `InputKey` for each property.
However, `InputKeys` are also created from `CodingKeys` during decoding of a command. These `CodingKeys` _do not_ have the leading underscore that is added by the property wrapper, so any underscores that appear are actually from the declaration of the property with an underscored name. Removing leading underscores from `CodingKey` names results in a mismatch when trying to find the …
=> Stop removing underscores from CodingKey names in InputKey

Sources/ArgumentParser/Parsable Types/ParsableCommand.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Parsing/ParsedValues.swift, Sources/ArgumentParser/Parsing/SplitArguments.swift, Tests/ArgumentParserEndToEndTests/RepeatingEndToEndTests+ParsingStrategy.swift
Arguments declared with the `.allUnrecognized` parsing strategy currently capture built-in flags, which isn't intended. This fixes that issue by looking for built-in flags in the captured portion of the input before decoding.
Fixes rdar://104990388
=> Don't let .allUnrecognized consume built-in flags

Tests/ArgumentParserGenerateManualTests/MathGenerateManualTests.swift, Tools/generate-manual/DSL/Document.swift, Tools/generate-manual/DSL/SinglePageDescription.swift
Fixes #551
- Fixes a bug where signle-page manuals did not include subcommand abstracts because the DSL logic did not take to account root commands vs subcommands. This change adds a "root" property to the DSL element to allow for styling differences in the two cases.
Thanks @Nef10 for reporting this issue. If you have time could you try this branch and verify it solves the issue in your project.
=> Add subcommand abstract to single-page manuals

Sources/ArgumentParser/Parsing/ArgumentDecoder.swift, Tests/ArgumentParserEndToEndTests/UnparsedValuesEndToEndTest.swift
As initially demonstrated in #553, the existing `ArgumentDecoder` logic fails when presented with a property which:
- Is unparsed
- Is not optional
- Has a default value, and
- Requests a keyed container during decoding
This occurs because while the actual property in question is properly assessed as having `.defaultValue` as an `InputOrigin`, the request for a keyed decoding container bypasses the logic which would otherwise return said default value, and since the `ArgumentDefinition` logic is (correctly) not recursive, the type fails to decode any keys it contains due to a "missing value".
The most straightforward solution I could find, one which covers all cases without negatively affecting handling of parsed properties (to the best of my ability to determine), was to apply the …
=> Handle unparsed non-optional complex property types

Examples/count-lines/CountLines.swift, Tests/ArgumentParserExampleTests/CountLinesExampleTests.swift
CI is allowing a `guard #available(macOS 12)` in the tests to pass, but then reporting macOS version 10.16 both in ProcessInfo and in the guard in the actual `CountLines.run()` method, which results in an inconsistency. Skipping the test under these conditions until we can sort out the configuration issue.
=> Skip count-lines tests in CI for now

Sources/ArgumentParser/Utilities/Platform.swift
Since Musl is sufficiently different from Glibc (see https://wiki.musl-libc.org/functional-differences-from-glibc.html), it requires a different import, which now should be applied to files that have `import Glibc` in them.
=> Add support for Musl libc

Sources/ArgumentParserTestHelpers/CMakeLists.txt
The `ArgumentParserTestHelpers` module depends on
`ArgumentParserToolInfo` but fails to indicate that dependency.  This was exposed whilst improving static linking for Windows.
=> build: add missing static link dependency

Sources/ArgumentParser/Documentation.docc/Articles/DeclaringArguments.md
Document ability to skip unknown parameters passed as command input
Fix #571
=> Document ability to skip unknown parameters

Tools/changelog-authors/ChangelogAuthors.swift, Tools/changelog-authors/Models.swift
Apparently the `commit.authors` field is optional - this fix skips commits without an author.
=> Update GH models in changelog-authors

Sources/ArgumentParser/Parsable Properties/OptionGroup.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests+GroupName.swift
When option groups are nested, any titles of the nested groups are removed, even when the containing group doesn't have a title. This change preserves the nested groups' titles when grouped in an untitled option group. Nesting within a titled option group continues to override any nested option groups.
Fixes #585.
=> Don't remove nested option group titles

Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Usage/DumpHelpGenerator.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Sources/ArgumentParserTestHelpers/TestHelpers.swift, Sources/ArgumentParserToolInfo/ToolInfo.swift, Tests/ArgumentParserUnitTests/DumpHelpGenerationTests.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
Renames an internal property of argument parser to simplify tracking values through the code base. Should have no functional changes.
=> Rename allValues to allValueStrings

Sources/ArgumentParser/Completions/BashCompletionsGenerator.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift, Tests/ArgumentParserUnitTests/CompletionScriptTests.swift
This PR implements two TODOs left over in the Bash completion script generator code:
1. `CompletionKind.file(extensions:)` did not actually honor the `extensions` array. It now does so.
2. `CompletionKind.file(extensions:)` and `.directory` now both preferentially invoke the `_filedir` shell function from `bash-completion` ([v1 for Bash 3.2](https://salsa.debian.org/debian/bash-completion) & [v2 for Bash 4.2+](https://github.com/scop/bash-completion)), if it is available in the shell environment at the time, falling back on `compgen` if it is not.
_Note: I could not find any open issues referring to these concerns._
=> [Bash completion]: Respects .file() extensions, uses _filedir 

Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Usage/MessageInfo.swift, Sources/ArgumentParser/Utilities/Platform.swift, Sources/ArgumentParserTestHelpers/TestHelpers.swift, Tests/ArgumentParserEndToEndTests/UnparsedValuesEndToEndTest.swift, Tests/ArgumentParserExampleTests/CountLinesExampleTests.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift, Tests/ArgumentParserExampleTests/RepeatExampleTests.swift, Tests/ArgumentParserExampleTests/RollDiceExampleTests.swift, Tests/ArgumentParserPackageManagerTests/HelpTests.swift, Tests/ArgumentParserPackageManagerTests/Tests.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
As documented in both the [Linux](https://man7.org/linux/man-pages/man7/environ.7.html:~:text=COLUMNS) and [BSD](https://man.freebsd.org/cgi/man.cgi?environ(7)#:~:text=COLUMNS) versions of the `environ(7)` manpage, many console utilities respect the presence of the `COLUMNS` and `LINES` environment variables, treating them as overrides (or, less commonly, fallbacks) of the terminal's reported size (if any). This adds that same behavior to ArgumentParser's screen size logic, affecting the wrapping of the usage generator's output.
_Note: These changes follow the semantics of `ls(1)`, where `COLUMNS` and `LINES` individually override the values reported by a terminal when they are present. Setting only one of the two variables has no effect on the other. It is also worth noting that at the …
=> Respect the COLUMNS and LINES environment variables when present

README.md, Sources/ArgumentParser/Documentation.docc/ArgumentParser.md, Sources/ArgumentParser/Documentation.docc/Articles/GettingStarted.md, Sources/ArgumentParser/Documentation.docc/Articles/Validation.md
Update to README and markdown documentation to include easily discovered references to `AsyncParsableCommand`.
In issue https://github.com/apple/swift-argument-parser/issues/561, I noted that `AsyncParsableCommand` was not easily discovered. This pull request attempts to remedy this by adding simple references to it in `README.md`, `ArgumentParser.md`, and `Validation.md`. In `GettingStarted.md` I went so far as to add a new section with an example.
Please note, this only includes documentation changes and does not include any code changes. Therefore, there are no tests for this PR.
=> Add AsyncParsableCommand to README

Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Parsable Types/ParsableCommand.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Sources/ArgumentParser/Utilities/Platform.swift
Resolves warnings around accessing `CommandLine.arguments` and the shared `Platform.standardError`.
=> Workarounds for remaining concurrency warnings

Sources/ArgumentParser/Completions/BashCompletionsGenerator.swift, Tests/ArgumentParserUnitTests/CompletionScriptTests.swift
If a ParsableCommand has a `commandName` value with a hyphen, the bash completion generator will generate a function name with a hyphen which isn't valid in BASH, eg `_programName_command_sub-command': not a valid identifier`
=> Bash does not like '-' in function names

Tests/ArgumentParserUnitTests/HelpGenerationTests.swift, Tests/ArgumentParserUnitTests/SplitArgumentTests.swift, Tools/generate-manual/Extensions/Date+ExpressibleByArgument.swift
These warnings are showing up in tests about types and protocols that are defined within this package, so they don't pose a problem for future library evolution. Instead of using the `@retroactive` attribute, which isn't supported by older compilers, this change fully qualifies the type and protocol in the relevant conformance declarations, which suppresses the issue.
Re: https://github.com/apple/swift-evolution/blob/main/proposals/0364-retroactive-conformance-warning.md
=> [NFC] Suppress retroactive conformance errors

Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
These use APIs which are not available on Windows, so skipping the test is insufficient as it does not build.
=> Tests: repair the build on Windows

Sources/ArgumentParser/Parsing/ArgumentSet.swift, Tests/ArgumentParserEndToEndTests/RepeatingEndToEndTests.swift
Fixes an issue where a single attached value triggered an error on `.upToNextOption` options.
Fixes #609.
=> Allow single, attached value with .upToNextOption

CHANGELOG.md
This adds a note about mutations to `CommandLine.arguments` no longer being used.
=> Add note about CL.arguments to the changelog

Sources/ArgumentParser/Parsing/CommandParser.swift, Tests/ArgumentParserEndToEndTests/DefaultSubcommandEndToEndTests.swift
When there's a default subcommand that captures pass-through args, only a standalone help flag should trigger help (since the flag should otherwise go to the subcommand). This fix makes that true for single- dash help flag names, which were previously being skipped, due to single-dash flags being lexed as both one whole flag and as a group of individual short flags.
Re: https://github.com/apple/swift-package-manager/issues/7218
Re: rdar://120422808
=> Fix unrecognized `-help` flag with default command

Sources/ArgumentParser/Parsable Types/CommandConfiguration.swift
Lack of this marker protocol conformance causes warnings with strict concurrency checks, such as `Static property 'configuration' is not concurrency-safe because it is not either conforming to 'Sendable' or isolated to a global actor; this is an error in Swift 6`
=> Mark `CommandConfiguration` as `Sendable`

Sources/ArgumentParser/Usage/DumpHelpGenerator.swift, Sources/ArgumentParser/Usage/MessageInfo.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift
These annotations produce warnings when compiling swift-syntax without library evolution using Swift ≥5.10.
Replace them by `private import` when compiling using Swift ≥5.11.
Mirrors https://github.com/apple/swift-syntax/pull/2429
=> Remove `@_implementationOnly` annotations

Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift, Tests/ArgumentParserUnitTests/CompletionScriptTests.swift
Some commands allow an option to be repeated to provide multiple values. For example, ssh allows the -L flag to be repeated to establish multiple port forwardings.
ArgumentParser supports this style when the Option value is an Array and the parsingStrategy is ArrayParsingStrategy.singleValue or .unconditionalSingleValue.
Without this patch, ArgumentParser generates a zsh completion script that does not handle repeatable options correctly. The generated script suppresses completion of any option after that option's first use, even if the option is repeatable.
With this patch, ArgumentParser generates a zsh completion script that allows a repeatable option to be completed each time it is used.
The relevant zsh _arguments syntax is documented here: …
=> Improve zsh completion for repeatable options (#564)

Examples/math/Math.swift, Sources/ArgumentParser/Documentation.docc/Articles/CommandsAndSubcommands.md, Sources/ArgumentParser/Documentation.docc/Articles/CustomizingCommandHelp.md, Sources/ArgumentParser/Usage/HelpCommand.swift, Tests/ArgumentParserEndToEndTests/DefaultSubcommandEndToEndTests.swift, Tests/ArgumentParserEndToEndTests/DefaultsEndToEndTests.swift, Tests/ArgumentParserEndToEndTests/NestedCommandEndToEndTests.swift, Tests/ArgumentParserEndToEndTests/SubcommandEndToEndTests.swift, Tests/ArgumentParserPackageManagerTests/HelpTests.swift, Tests/ArgumentParserPackageManagerTests/PackageManager/GenerateXcodeProject.swift, Tests/ArgumentParserPackageManagerTests/PackageManager/Options.swift, Tests/ArgumentParserUnitTests/CompletionScriptTests.swift, Tests/ArgumentParserUnitTests/ExitCodeTests.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
Prefer `let` for private configurations.
Otherwise, we may think that the configuration is mutable, which is not really sendable friendly.
=> Prefer `let` for private configurations

Sources/ArgumentParser/Documentation.docc/Extensions/Option.md, Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsable Properties/Option.swift, Tests/ArgumentParserEndToEndTests/OptionalEndToEndTests.swift
Due to the restructuring in #477, there was ambiguity between the unconstrained `@Option` initializer that uses a transform (but no initial value) and the one that is constrained to the property being optional. This marks the unconstrained version as disfavored, which allows overload resolution to select the optional version when appropriate.
Fixes #618.
=> Fix for `@Option(transform:)` with optional type

Sources/ArgumentParser/Parsable Properties/Argument.swift
=> Clarify `postTerminator` parsing strategy behavior

Examples/math/Math.swift, Sources/ArgumentParser/Documentation.docc/Articles/CommandsAndSubcommands.md, Sources/ArgumentParser/Documentation.docc/Extensions/CommandConfiguration.md, Sources/ArgumentParser/Parsable Types/CommandConfiguration.swift, Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Sources/ArgumentParser/Utilities/Tree.swift, Tests/ArgumentParserEndToEndTests/NestedCommandEndToEndTests.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift, Tests/ArgumentParserUnitTests/TreeTests.swift
This adds support for aliases for subcommands via a new parameter to `CommandConfiguration`'s constructors. The aliases are passed as an array of strings, where the default is just an empty array that signifies there are no aliases. The aliases are supported regardless of if a different commandName is chosen or not. This also updates how subcommands show up in the help text; any aliases are now displayed to the right of the original command.
In addition to the functionality itself, this change:
1. Updates some of the EndToEnd parsing tests to make sure they function while using aliases.
2. Sprinkles mentions where I saw fit in the documentation.
3. Updates the Math example to have aliases for `math stats average` (`math stats avg`), and `math multiply` (`math mul`).
`math`'s help text now …
=> Add aliases support for sub commands

Sources/ArgumentParser/Parsable Types/ParsableArguments.swift, Sources/ArgumentParser/Parsable Types/ParsableCommand.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
Adds a new API to ParsableArguments and ParsableCommand for getting the usage string. This allows clients to use argument-parser in a more piecemeal way to construct their own error screens.
=> Add ParsableArguments/Command.usageString

Sources/ArgumentParser/Parsable Types/CommandConfiguration.swift, Sources/ArgumentParserTestHelpers/TestHelpers.swift
When the old (pre-aliases) initializer has all its default parameter
values, it is selected as the overload because it has fewer parameters
overall. Removing the default parameters allows it to still satisfy
(very niche) source compat requirements without actually being
available as an overload.
=> Eliminate warnings re: CommandConfiguration init

Examples/count-lines/CountLines.swift
`CountLines.swift` uses the mix of the normal if-let and the shorthand. This PR changes the normal version to the shorthand to stay consistent.
- N/A I've added at least one test that validates that my change is working, if appropriate
- N/A I've updated the documentation if necessary
=> Prefer if-let shorthand in `CountLines.swift`

Sources/ArgumentParser/Parsable Types/AsyncParsableCommand.swift, Tests/ArgumentParserEndToEndTests/AsyncCommandEndToEndTests.swift, Tests/ArgumentParserEndToEndTests/CMakeLists.txt
Adds a new static main function to `AsyncParsableCommand` to allow users to manually pass in arguments. The new functions behaves identically to the version found in `ParsableCommand` (see: https://github.com/apple/swift-argument-parser/blob/main/Sources/ArgumentParser/Parsable%20Types/ParsableCommand.swift#L126). This functionality is useful for manually building an argument list, e.g. when building a busybox~like binary.
=> Support passing arguments to async main

Sources/ArgumentParser/Utilities/Platform.swift
This new overlay was recently added to trunk in swiftlang/swift#72161 and swiftlang/swift#72634, then to 6.0 in swiftlang/swift#74758. I've been building it with this patch on my daily Android CI since the trunk addition, finagolfin/swift-android-sdk#151, and natively on Android too.
@natecook1000, an easy review.
=> Import new Android overlay

Sources/ArgumentParser/Parsable Properties/OptionGroup.swift
The documentation as presented doesn't compile. An initializer is required for a boolean flag.
rdar://132579907
=> Add missing @Flag initializer in example

Tests/ArgumentParserGenerateManualTests/MathGenerateManualTests.swift, Tools/generate-manual/DSL/ArgumentSynopsis.swift, Tools/generate-manual/DSL/MultiPageDescription.swift, Tools/generate-manual/DSL/SinglePageDescription.swift
Resolves issue #665, which suppresses the output for arguments that are marked as `hidden` - from synopsis, single page output, and multi-page output for generate-manual.
=> Exclude hidden argument content from generate-manual output

Sources/ArgumentParser/Usage/DumpHelpGenerator.swift, Sources/ArgumentParserToolInfo/ToolInfo.swift, Tests/ArgumentParserUnitTests/DumpHelpGenerationTests.swift
- resolves https://github.com/apple/swift-argument-parser/issues/668 by extending the ToolInfoV0 (help dump) struct to include visibility information for commands (already exists for arguments).
- updates test output to verify existing examples extend with the additional key.
=> extend ToolInfoV0 with command visibility

Package.swift, Sources/ArgumentParserToolInfo/ToolInfo.swift, Tests/ArgumentParserUnitTests/DumpHelpGenerationTests.swift, Tools/generate-manual/GenerateManual.swift
Fixed all Swift 5.7 build breaks in `main`, namely:
- `Package.swift`: `target` array missing a comma
- `ToolInfo.swift`: contains 2 if expressions, which are not supported by Swift 5.7
- `GenerateManual.swift`: contains switch expression, which is not supported by Swift 5.7
- `DumpHelpGenerationTests.swift`: contains switch expression, which is not supported by Swift 5.7
Resolve #675
=> Fix Swift 5.7 build errors

Sources/ArgumentParser/CMakeLists.txt
Add the missing source file to the package to allow building with CMake again.
=> build: repair the CMake based build

README.md, Sources/ArgumentParser/Documentation.docc/Articles/GettingStarted.md, Sources/ArgumentParser/Documentation.docc/Extensions/AsyncParsableCommand.md
Fix incorrect or confusing documentation about Swift versions
Rewrote Markdown to properly specify Swift 5.7 instead of 5.5, and to clarify other information related to Swift versions.
Resolve #677
=> Fix incorrect or confusing documentation about Swift versions

Sources/ArgumentParser/Completions/BashCompletionsGenerator.swift, Sources/ArgumentParser/Completions/CompletionsGenerator.swift, Sources/ArgumentParser/Completions/FishCompletionsGenerator.swift, Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift, Sources/ArgumentParser/Documentation.docc/Articles/CustomizingCompletions.md, Sources/ArgumentParser/Parsing/CommandParser.swift, Tests/ArgumentParserExampleTests/MathExampleTests.swift, Tests/ArgumentParserUnitTests/CompletionScriptTests.swift, Tests/ArgumentParserUnitTests/RequestingCompletionScriptTests.swift
Add singleton to indicate which shell is requesting completion candidates.
A `CompletionShell` singleton named `CompletionShell.requesting` has been created that indicates which shell is requesting completion candidates.
The singleton is populated when a completion script is generated, so functions used to generate arguments for `CompletionKind` creation functions can read the singleton to be able to return completion candidates / shell commands tailored for the requesting shell.
For the `custom(:)` `CompletionKind` creation function, the singleton is populated at runtime (when a completion script requests completions from the Swift app after a user types tab while composing a command line to call the app).
The requesting shell is communicated to the Swift app via an environment variable …
=> Add singleton to indicate which shell is requesting completion candidates

CMakeLists.txt, cmake/modules/SwiftSupport.cmake
Previously, libraries were installed under `lib/swift/${os}/`. They should be installed in the default library directory for the relevant target system.
In addition, swiftmodules were installed in the older layout format on non-Darwin platforms. This changes to use the standard modern layout format for swiftmodules.
=> [cmake] Install libraries in standard directories

Package.swift, Package@swift-5.8.swift, Sources/ArgumentParserToolInfo/ToolInfo.swift, Tests/ArgumentParserToolInfoTests/ArgumentParserToolInfoTests.swift, Tests/ArgumentParserToolInfoTests/Examples/example0.json, Tests/ArgumentParserToolInfoTests/Examples/example1.json
Adds a new test target called ArgumentParserToolInfoTests which contains example json output from dump-help. The test code attempts to parse all json files in the 'Examples' subdirectory. This will help us catch cases where ArgumentParser is unable to parse json generated by older versions.
We still need to add a test that asserts old ArgumentParser versions can parse the output of new versions.
=> Add tests parsing dump help output

Sources/ArgumentParser/Parsable Properties/ArgumentDiscussion.swift, Sources/ArgumentParser/Usage/DumpHelpGenerator.swift, Sources/ArgumentParserToolInfo/ToolInfo.swift, Tests/ArgumentParserGenerateManualTests/ColorGenerateManualTests.swift, Tests/ArgumentParserGenerateManualTests/MathGenerateManualTests.swift, Tests/ArgumentParserUnitTests/DumpHelpGenerationTests.swift, Tools/generate-manual/DSL/Discussion.swift, Tools/generate-manual/DSL/MultiPageDescription.swift, Tools/generate-manual/DSL/SinglePageDescription.swift
Cleans up some lingering odds and ends from #647. Specifically switches
CommandInfoV0 to use the old style description and updates
ArgumentInfoV0 to emit value descriptions as a separate dictionary.
=> Refactor serialization of dump help descriptions

Sources/ArgumentParser/Completions/CompletionsGenerator.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Utilities/Mutex.swift
Moves static read-only vars behind a mutex so they are currency safe. Users of the api don't need to worry about this because the mutex is hidden behind an accessor.
=> Fix concurrency warnings

.github/workflows/lint.yml, Sources/ArgumentParser/Documentation.docc/Articles/CustomizingCommandHelp.md, Sources/ArgumentParser/Documentation.docc/Articles/CustomizingHelp.md, Sources/ArgumentParser/Documentation.docc/Articles/DeclaringArguments.md, Sources/ArgumentParser/Documentation.docc/Articles/ExperimentalFeatures.md, Sources/ArgumentParser/Documentation.docc/Articles/GettingStarted.md, Sources/ArgumentParser/Documentation.docc/Articles/ManualParsing.md, Sources/ArgumentParser/Documentation.docc/Articles/Validation.md, Sources/ArgumentParser/Documentation.docc/Extensions/CommandConfiguration.md, Sources/ArgumentParser/Parsable Properties/Argument.swift, Sources/ArgumentParser/Parsable Properties/Errors.swift, Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsable Properties/Option.swift, Sources/ArgumentParser/Parsable Types/ParsableCommand.swift
Enables the documentation check from the swiftlang soundness workflow and resolves errors/notes emitted by the check.
Fixes: #704
=> Enable Documentation check

Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Usage/DumpHelpGenerator.swift, Sources/ArgumentParser/Usage/MessageInfo.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Sources/ArgumentParser/Utilities/Mutex.swift
The `@_implementationOnly` attribute does not work correctly without library evolution enabled. The only possible client with this enabled is Apple, however they have updated to the Swift 6 compiler and can use `internal import` instead of this attribute. Therefore there is no need for this package to use the attribute anymore.
=> Remove `@_implementationOnly` imports

Sources/ArgumentParser/Parsing/CommandParser.swift
Make `CommandParser.swift` import Swift version consistent with other files.
Resolve #723
=> Make CommandParser.swift import Swift version consistent with other files

Sources/ArgumentParser/Parsing/ArgumentSet.swift, Sources/ArgumentParser/Parsing/InputOrigin.swift, Sources/ArgumentParser/Parsing/ParserError.swift, Sources/ArgumentParser/Usage/UsageGenerator.swift, Tests/ArgumentParserUnitTests/ParsableArgumentsValidationTests.swift
When a required option has a short name, longer single-dash arguments can end up incorrectly colliding and causing confusing error messages. This changes the error handling when a short-name option is missing a value to show both the missing-value error _and_ a message about the unrecognized longer/composite option.
Fixes #709.
=> Fix confusing error message w/ single-dash option

Sources/ArgumentParser/Usage/DumpHelpGenerator.swift, Sources/ArgumentParserTestHelpers/TestHelpers.swift, Tools/generate-docc-reference/Extensions/Process+SimpleAPI.swift, Tools/generate-manual/Extensions/Process+SimpleAPI.swift
As @rgoldberg points out, the bump to Swift 5.7 makes these availability checks unnecessary.
Fixes #725.
=> Drop availability checks for macOS 10.13

Sources/ArgumentParser/CMakeLists.txt
Recently, `Sources/ArgumentParser/Utilities/Mutex.swift` was created but omitted in `CMakeLists.txt`
=> Update ArgumentParser CMakeLists.txt: add Mutex.swift

Sources/ArgumentParser/Parsable Types/ParsableCommand.swift
If the synchronous `main()` is running for an `AsyncParsableCommand` root, something went wrong. Previously, this was only diagnosed when there was an async subcommand; this change expands the failure condition to include standalone async commands.
Fixes #662.
(Tested locally, since we don't have crash tests.)
=> Simplify configuration check for async root command

Sources/ArgumentParser/Completions/BashCompletionsGenerator.swift, Sources/ArgumentParser/Completions/CompletionsGenerator.swift, Tests/ArgumentParserExampleTests/Snapshots/testMathBashCompletionScript().bash, Tests/ArgumentParserUnitTests/Snapshots/testBase_Bash().bash
Improve bash completion script generation.
There are many issues with script generation. Some of them are documented in #679 & its comments.
This issue is for a first batch of bash completion script fixes.
Each commit should note the fix(es) that it contains.
Note that I use "iff" in some Swift & bash comments, but not in code or in DocC. If you want "iff" removed from comments, please let me know.
Will rebase if `main` is updated (especially if #726 is merged).
Resolve #734
=> Improve bash completion script generation

Examples/count-lines/CountLines.swift
Noticed that the ArgumentParser [build matrix on Swift Package Index](https://swiftpackageindex.com/apple/swift-argument-parser/builds) is not great; this should help.
=> Specify availability for remainder of platforms

Sources/ArgumentParser/Completions/CompletionsGenerator.swift, Sources/ArgumentParser/Parsable Properties/Errors.swift, Sources/ArgumentParser/Parsable Properties/Flag.swift, Sources/ArgumentParser/Parsable Types/ParsableArgumentsValidation.swift, Sources/ArgumentParser/Usage/HelpGenerator.swift, Tests/ArgumentParserEndToEndTests/DefaultsEndToEndTests.swift, Tests/ArgumentParserEndToEndTests/SourceCompatEndToEndTests.swift
=> Fix several one-line summary doc comment issues

Sources/ArgumentParserTestHelpers/TestHelpers.swift, Tests/ArgumentParserGenerateDoccReferenceTests/GenerateDoccReferenceTests.swift, Tests/ArgumentParserGenerateDoccReferenceTests/Snapshots/testColorMarkdownReference().md, Tests/ArgumentParserGenerateDoccReferenceTests/Snapshots/testCountLinesMarkdownReference().md, Tests/ArgumentParserGenerateDoccReferenceTests/Snapshots/testMathMarkdownReference().md, Tests/ArgumentParserGenerateDoccReferenceTests/Snapshots/testRepeatMarkdownReference().md, Tests/ArgumentParserGenerateDoccReferenceTests/Snapshots/testRollMarkdownReference().md, Tools/generate-docc-reference/Extensions/ArgumentParser+Markdown.swift, Tools/generate-docc-reference/GenerateDoccReference.swift, Tools/generate-manual/GenerateManual.swift
- added a Boolean to distinguish regular (GH-flavored) markdown from docc-flavored markdown
- represent the arguments in generated files with term lists for the docc-flavored variant
- updated the snapshot tests to work both GH and DocC flavored markdown generation
- removed an added "\n" in the recording of content for snapshot tests, which caused the snapshot tests some issues (recorded tests with new values wouldn't pass on second-run)
resolves #721
=> display arguments as term lists in docc-flavored markdown generation

Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift, Sources/ArgumentParser/Parsable Properties/CompletionKind.swift, Tests/ArgumentParserExampleTests/Snapshots/testMathZshCompletionScript().zsh, Tests/ArgumentParserUnitTests/Snapshots/testBase_Zsh().zsh
Improve CompletionKind DocC.
Do not merge until after #738 has been merged.
Resolve #739
=> Improve CompletionKind DocC

Tests/ArgumentParserGenerateDoccReferenceTests/Snapshots/testColorDoccReference().md, Tests/ArgumentParserGenerateDoccReferenceTests/Snapshots/testCountLinesDoccReference().md, Tests/ArgumentParserGenerateDoccReferenceTests/Snapshots/testMathDoccReference().md, Tests/ArgumentParserGenerateDoccReferenceTests/Snapshots/testRepeatDoccReference().md, Tests/ArgumentParserGenerateDoccReferenceTests/Snapshots/testRollDoccReference().md, Tools/generate-docc-reference/Extensions/ArgumentParser+Markdown.swift
resolves #772 
The term list output originally followed the markdown format and embedded the trailing `:` in the bold section, but DocC doesn't recognize the list element as a term list if the `:` is embedded, only if it's trailing. This PR resolves that situation, and updates the associated snapshot tests.
=> fixes misformating of docc term list output

Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift, Tests/ArgumentParserExampleTests/Snapshots/testMathZshCompletionScript().zsh, Tests/ArgumentParserUnitTests/Snapshots/testBase_Zsh().zsh
Preserve order of supplied zsh completion candidates.
Resolve #774
=> Preserve order of supplied zsh completion candidates

Examples/math/Math.swift, Sources/ArgumentParser/Parsable Properties/CompletionKind.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParserToolInfo/ToolInfo.swift
Replace the cursor index within the completing word parameter of custom-completion closures with a `String` completion prefix parameter.
Resolve #769
@natecook1000 @rauhul I think that this is an urgent improvement.
The Swift substring API is exceedingly verbose, and this will make using custom completions much easier.
We don't want to release the current API with the 2 indices to users because then it will need to be supported indefinitely, despite being suboptimal.
=> Replace the cursor index within the completing word parameter of custom-completion closures with a `String` completion prefix parameter

Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift, Tests/ArgumentParserExampleTests/Snapshots/testMathZshCompletionScript().zsh, Tests/ArgumentParserUnitTests/Snapshots/testBase_Zsh().zsh
Allow zsh repeating positionals to be completed multiple times.
Resolve #776
=> Allow zsh repeating positionals to be completed multiple times

Sources/ArgumentParser/CMakeLists.txt, Sources/ArgumentParserTestHelpers/CMakeLists.txt
When building without `-DFoundation_DIR=...`, we should not wire up a dependency on Foundation and instead rely on autolinking and the driver to collude to resolve the linkage. Failure to do so will instill a rogue `-lFoundation.lib` when linking on Windows.
=> build: conditionally add Foundation dependency edge

CHANGELOG.md
Going to merge this to do a quick release of 1.5.1.
@rauhul @rgoldberg Happy to take refinements / expansions of anything in the unreleased section!
=> Update changelog for 1.5.1, along with unreleased changes

Sources/ArgumentParser/Completions/BashCompletionsGenerator.swift, Sources/ArgumentParser/Completions/FishCompletionsGenerator.swift, Sources/ArgumentParser/Completions/ZshCompletionsGenerator.swift, Sources/ArgumentParser/Parsable Properties/CompletionKind.swift, Sources/ArgumentParser/Parsing/CommandParser.swift, Sources/ArgumentParser/Usage/DumpHelpGenerator.swift, Sources/ArgumentParserToolInfo/ToolInfo.swift, Tests/ArgumentParserUnitTests/CompletionScriptTests.swift
Support async custom completion closures.
Resolve #555
=> Support async custom completion closures

Sources/ArgumentParser/Utilities/SwiftExtensions.swift, Tests/ArgumentParserEndToEndTests/PositionalEndToEndTests.swift
This change addresses a source break around conditional conformances to `ExpressibleByArgument` and `ParsableArgument` that I didn't anticipate, and eliminates the unneeded runtime presence of `_SendableMetatype`.
=> Designate `_SendableMetatype` as a marker protocol

Sources/ArgumentParser/Parsable Properties/ArgumentDiscussion.swift, Sources/ArgumentParser/Parsable Properties/Option.swift, Sources/ArgumentParser/Parsing/ArgumentDefinition.swift, Tests/ArgumentParserUnitTests/HelpGenerationTests.swift
Adding an `@Option` that is an Array of Enum flag did not display the help message correctly.
Update the HelpGenerator to handle this case.
Fixes: #818
=> Properly display help message of array of enum items option

.github/workflows/pull_request.yml
This configuration is no longer enabled in CI.
=> Exclude Xcode 16.2 from CI testing
